"""Starter catalog for the general differential workbench.

The catalog is intentionally explicit and conservative. It is not a complete
disease database; it is the first source-linked layer for the stepwise generic
workflow.
"""

CATALOG_VERSION = "general-differential-starter-2026-06-28"

URGENCY_ORDER = {
    "emergent": 0,
    "urgent": 1,
    "soon": 2,
    "routine": 3,
}

SOURCES = {
    "aha_heart_attack": {
        "publisher": "American Heart Association",
        "title": "Warning Signs of a Heart Attack",
        "url": "https://www.heart.org/en/health-topics/heart-attack/warning-signs-of-a-heart-attack",
    },
    "asa_stroke": {
        "publisher": "American Stroke Association",
        "title": "Stroke Symptoms and Warning Signs",
        "url": "https://www.stroke.org/en/about-stroke/stroke-symptoms",
    },
    "cdc_sepsis": {
        "publisher": "CDC",
        "title": "Sepsis",
        "url": "https://www.cdc.gov/sepsis/index.html",
    },
    "cdc_sepsis_signs": {
        "publisher": "CDC",
        "title": "Sepsis Signs and Symptoms",
        "url": "https://www.cdc.gov/sepsis/communication-resources/gaos-signs-symptoms.html",
    },
    "nice_chest_pain": {
        "publisher": "NICE CKS",
        "title": "Chest pain",
        "url": "https://cks.nice.org.uk/topics/chest-pain/",
    },
    "nice_acute_abdomen": {
        "publisher": "NICE CKS",
        "title": "Abdominal pain - acute",
        "url": "https://cks.nice.org.uk/topics/abdominal-pain-acute/",
    },
    "merck_professional": {
        "publisher": "Merck Manual Professional",
        "title": "Professional clinical reference",
        "url": "https://www.merckmanuals.com/professional",
    },
    "merck_headache_red_flags": {
        "publisher": "Merck Manual Professional",
        "title": "Matching Red Flag Findings With a Cause for Headache",
        "url": "https://www.merckmanuals.com/professional/multimedia/table/matching-red-flag-findings-with-a-cause-for-headache",
    },
    "merck_neutropenia": {
        "publisher": "Merck Manual Professional",
        "title": "Neutropenia",
        "url": "https://www.merckmanuals.com/professional/hematology-and-oncology/leukopenias/neutropenia",
    },
    "merck_cancer_therapy_adverse_effects": {
        "publisher": "Merck Manual Professional",
        "title": "Management of Adverse Effects of Cancer Therapy",
        "url": "https://www.merckmanuals.com/professional/oncology/principles-of-cancer-therapy/management-of-adverse-effects-of-cancer-therapy",
    },
    "nice_spinal_metastases_mscc": {
        "publisher": "NICE",
        "title": "Spinal metastases and metastatic spinal cord compression",
        "url": "https://www.ncbi.nlm.nih.gov/books/NBK595817/",
    },
    "merck_all": {
        "publisher": "Merck Manual Professional",
        "title": "Acute Lymphoblastic Leukemia (ALL)",
        "url": "https://www.merckmanuals.com/professional/oncology/leukemias/acute-lymphoblastic-leukemia-all",
    },
    "canadian_cancer_hypercalcemia": {
        "publisher": "Canadian Cancer Society",
        "title": "High calcium levels",
        "url": "https://cancer.ca/en/treatments/side-effects/high-calcium-levels",
    },
    "merck_urinary_retention": {
        "publisher": "Merck Manual Professional",
        "title": "Urinary Retention",
        "url": "https://www.merckmanuals.com/professional/genitourinary-disorders/voiding-disorders/urinary-retention",
    },
    "niddk_urinary_retention": {
        "publisher": "NIDDK",
        "title": "Symptoms and Causes of Urinary Retention",
        "url": "https://www.niddk.nih.gov/health-information/urologic-diseases/urinary-retention/symptoms-causes",
    },
    "merck_pid": {
        "publisher": "Merck Manual Professional",
        "title": "Pelvic Inflammatory Disease (PID)",
        "url": "https://www.merckmanuals.com/professional/gynecology-and-obstetrics/vaginitis-cervicitis-and-pelvic-inflammatory-disease/pelvic-inflammatory-disease-pid",
    },
    "cdc_pid": {
        "publisher": "CDC",
        "title": "Pelvic Inflammatory Disease (PID) - STI Treatment Guidelines",
        "url": "https://www.cdc.gov/std/treatment-guidelines/pid.htm",
    },
    "acog_acute_aub": {
        "publisher": "ACOG",
        "title": "Management of Acute Abnormal Uterine Bleeding in Nonpregnant Reproductive-Aged Women",
        "url": "https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2013/04/management-of-acute-abnormal-uterine-bleeding-in-nonpregnant-reproductive-aged-women",
    },
    "merck_vaginal_bleeding": {
        "publisher": "Merck Manual Professional",
        "title": "Vaginal Bleeding",
        "url": "https://www.merckmanuals.com/professional/gynecology-and-obstetrics/symptoms-of-gynecologic-disorders/vaginal-bleeding",
    },
    "merck_abnormal_uterine_bleeding": {
        "publisher": "Merck Manual Professional",
        "title": "Abnormal Uterine Bleeding",
        "url": "https://www.merckmanuals.com/professional/gynecology-and-obstetrics/abnormal-uterine-bleeding/abnormal-uterine-bleeding",
    },
    "nimh_suicide_warning_signs": {
        "publisher": "NIMH",
        "title": "Warning Signs of Suicide",
        "url": "https://www.nimh.nih.gov/health/publications/warning-signs-of-suicide",
    },
    "nice_psychosis": {
        "publisher": "NICE",
        "title": "Psychosis and schizophrenia in adults: prevention and management",
        "url": "https://www.nice.org.uk/guidance/cg178",
    },
    "camh_psychosis_screening": {
        "publisher": "CAMH",
        "title": "Psychosis: Screening and Assessment",
        "url": "https://www.camh.ca/en/professionals/treating-conditions-and-disorders/psychosis/psychosis---screening-and-assessment",
    },
    "merck_psychosis_medical_condition": {
        "publisher": "Merck Manual Professional",
        "title": "Psychotic Disorder Due to Another Medical Condition",
        "url": "https://www.merckmanuals.com/professional/psychiatric-disorders/schizophrenia-and-related-disorders/psychotic-disorder-due-to-another-medical-condition",
    },
    "nice_bipolar": {
        "publisher": "NICE",
        "title": "Bipolar disorder: assessment and management",
        "url": "https://www.nice.org.uk/guidance/cg185",
    },
    "merck_bipolar": {
        "publisher": "Merck Manual Professional",
        "title": "Bipolar Disorders",
        "url": "https://www.merckmanuals.com/professional/psychiatric-disorders/mood-disorders/bipolar-disorders",
    },
    "nimh_panic_disorder": {
        "publisher": "NIMH",
        "title": "Panic Disorder: What You Need to Know",
        "url": "https://www.nimh.nih.gov/health/publications/panic-disorder-when-fear-overwhelms",
    },
    "nhs_panic_disorder": {
        "publisher": "NHS",
        "title": "Panic disorder",
        "url": "https://www.nhs.uk/mental-health/conditions/panic-disorder/",
    },
    "nimh_eating_disorders": {
        "publisher": "NIMH",
        "title": "Eating Disorders: What You Need to Know",
        "url": "https://www.nimh.nih.gov/health/publications/eating-disorders",
    },
    "merck_anorexia_nervosa": {
        "publisher": "Merck Manual Professional",
        "title": "Anorexia Nervosa",
        "url": "https://www.merckmanuals.com/professional/psychiatric-disorders/feeding-and-eating-disorders/anorexia-nervosa",
    },
    "merck_bulimia_nervosa": {
        "publisher": "Merck Manual Professional",
        "title": "Bulimia Nervosa",
        "url": "https://www.merckmanuals.com/professional/psychiatric-disorders/feeding-and-eating-disorders/bulimia-nervosa",
    },
    "merck_abscesses": {
        "publisher": "Merck Manual Professional",
        "title": "Abscesses",
        "url": "https://www.merckmanuals.com/professional/infectious-diseases/biology-of-infectious-disease/abscesses",
    },
    "idsa_ssti_guideline": {
        "publisher": "IDSA",
        "title": "Skin and Soft Tissue Infections Guideline",
        "url": "https://www.idsociety.org/practice-guideline/skin-and-soft-tissue-infections/",
    },
    "cdc_shingles_clinical_features": {
        "publisher": "CDC",
        "title": "Clinical Features of Shingles (Herpes Zoster)",
        "url": "https://www.cdc.gov/shingles/hcp/clinical-signs/index.html",
    },
    "cdc_shingles_clinical_overview": {
        "publisher": "CDC",
        "title": "Clinical Overview of Shingles (Herpes Zoster)",
        "url": "https://www.cdc.gov/shingles/hcp/clinical-overview/index.html",
    },
    "merck_sjs_ten": {
        "publisher": "Merck Manual Professional",
        "title": "Stevens-Johnson Syndrome (SJS) and Toxic Epidermal Necrolysis (TEN)",
        "url": "https://www.merckmanuals.com/professional/dermatologic-disorders/hypersensitivity-and-reactive-skin-disorders/stevens-johnson-syndrome-sjs-and-toxic-epidermal-necrolysis-ten",
    },
    "dermnet_sjs_ten": {
        "publisher": "DermNet",
        "title": "Stevens Johnson Syndrome / Toxic Epidermal Necrolysis",
        "url": "https://dermnetnz.org/topics/stevens-johnson-syndrome-toxic-epidermal-necrolysis",
    },
}

FINDING_GROUPS = [
    {
        "group_zh": "立即安全狀態",
        "group_en": "Immediate safety",
        "findings": [
            ("hemodynamic_instability", "Hemodynamic instability", "血流動力不穩"),
            ("altered_mental_status", "Altered mental status", "意識或精神狀態改變"),
            ("respiratory_distress", "Respiratory distress", "呼吸窘迫"),
            ("severe_pain", "Severe pain", "劇烈疼痛"),
            ("syncope", "Syncope", "昏厥"),
            ("immunocompromised", "Immunocompromised", "免疫低下"),
            ("pregnancy_possible", "Pregnancy possible", "可能懷孕"),
            ("recent_trauma", "Recent trauma", "近期外傷"),
        ],
    },
    {
        "group_zh": "心肺",
        "group_en": "Cardiopulmonary",
        "findings": [
            ("chest_pain", "Chest pain", "胸痛"),
            ("dyspnea", "Dyspnea", "呼吸困難"),
            ("diaphoresis", "Diaphoresis", "冒冷汗"),
            ("radiating_arm_jaw_pain", "Arm or jaw radiation", "手臂或下顎放射痛"),
            ("pleuritic_pain", "Pleuritic pain", "吸氣或胸膜性疼痛"),
            ("hemoptysis", "Hemoptysis", "咳血"),
            ("unilateral_leg_swelling", "Unilateral leg swelling", "單側下肢腫脹"),
            ("tearing_back_pain", "Tearing back pain", "撕裂樣背痛"),
            ("orthopnea_edema", "Orthopnea or edema", "端坐呼吸或水腫"),
            ("wheeze", "Wheeze", "喘鳴"),
            ("cough_sputum", "Cough or sputum", "咳嗽或痰"),
            ("tachycardia", "Tachycardia", "心搏過速"),
        ],
    },
    {
        "group_zh": "神經與頭痛",
        "group_en": "Neurologic and headache",
        "findings": [
            ("neurologic_deficit", "Neurologic deficit", "神經學缺損"),
            ("unilateral_weakness", "Unilateral weakness", "單側無力"),
            ("speech_vision_changes", "Speech or vision changes", "言語或視覺改變"),
            ("thunderclap_headache", "Thunderclap headache", "雷擊樣頭痛"),
            ("neck_stiffness", "Neck stiffness", "頸部僵硬"),
            ("new_headache_after_50", "New headache after age 50", "50歲後新發頭痛"),
            ("jaw_claudication", "Jaw claudication", "下顎跛行"),
            ("eye_pain_redness", "Eye pain or redness", "眼痛或紅眼"),
        ],
    },
    {
        "group_zh": "腹部與泌尿",
        "group_en": "Abdominal and urinary",
        "findings": [
            ("abdominal_pain", "Abdominal pain", "腹痛"),
            ("rebound_guarding", "Rebound or guarding", "反彈痛或防禦"),
            ("rlq_pain", "Right lower quadrant pain", "右下腹痛"),
            ("ruq_pain", "Right upper quadrant pain", "右上腹痛"),
            ("postprandial_ruq_pain", "Postprandial RUQ pain", "飯後右上腹痛"),
            ("vomiting", "Vomiting", "嘔吐"),
            ("gi_bleeding", "GI bleeding", "腸胃道出血"),
            ("jaundice", "Jaundice", "黃疸"),
            ("dysuria", "Dysuria", "排尿疼痛"),
            ("inability_to_void", "Inability to void", "無法排尿"),
            ("flank_pain", "Flank pain", "腰側痛"),
            ("pelvic_pain", "Pelvic pain", "骨盆痛"),
        ],
    },
    {
        "group_zh": "婦科",
        "group_en": "Gynecologic",
        "findings": [
            ("vaginal_bleeding", "Vaginal bleeding", "陰道出血"),
            ("vaginal_discharge", "Vaginal discharge", "陰道分泌物"),
            (
                "cervical_motion_tenderness",
                "Cervical motion tenderness",
                "子宮頸移動痛",
            ),
        ],
    },
    {
        "group_zh": "心理與行為",
        "group_en": "Mental health and behavior",
        "findings": [
            ("suicidal_ideation", "Suicidal ideation", "自殺意念"),
            ("self_harm_behavior", "Self-harm behavior", "自傷行為"),
            (
                "hallucinations_delusions",
                "Hallucinations or delusions",
                "幻覺或妄想",
            ),
            ("severe_agitation", "Severe agitation", "嚴重激動"),
            (
                "decreased_need_for_sleep",
                "Decreased need for sleep",
                "睡眠需求降低",
            ),
            (
                "risky_impulsive_behavior",
                "Risky or impulsive behavior",
                "高風險或衝動行為",
            ),
            ("substance_use_concern", "Substance use concern", "物質使用疑慮"),
            (
                "restrictive_eating_or_weight_fear",
                "Restrictive eating or weight fear",
                "限制飲食或體重恐懼",
            ),
            ("purging_behavior", "Purging behavior", "催吐或清除行為"),
            (
                "binge_eating_loss_of_control",
                "Binge eating with loss of control",
                "暴食且失控感",
            ),
        ],
    },
    {
        "group_zh": "感染、代謝與皮膚",
        "group_en": "Infectious, metabolic, skin",
        "findings": [
            ("fever", "Fever", "發燒"),
            ("hypothermia", "Hypothermia", "低體溫"),
            ("rash", "Rash", "皮疹"),
            ("purulent_skin_lesion", "Purulent skin lesion", "化膿性皮膚病灶"),
            (
                "rapidly_spreading_skin_infection",
                "Rapidly spreading skin infection",
                "快速擴大的皮膚感染",
            ),
            (
                "vesicular_dermatomal_rash",
                "Vesicular dermatomal rash",
                "皮節水泡疹",
            ),
            ("mucosal_lesions", "Mucosal lesions", "黏膜病灶"),
            (
                "skin_sloughing_or_blistering",
                "Skin blistering or sloughing",
                "皮膚水泡或脫落",
            ),
            ("new_medication_exposure", "New medication exposure", "新用藥暴露"),
            ("facial_lip_tongue_swelling", "Face, lip, or tongue swelling", "臉唇舌腫"),
            ("extreme_thirst_polyuria", "Thirst or polyuria", "多渴或多尿"),
            ("hypoglycemia_risk", "Hypoglycemia risk", "低血糖風險"),
            ("weight_loss", "Weight loss", "體重減輕"),
            ("fatigue", "Fatigue", "疲倦"),
        ],
    },
    {
        "group_zh": "血液與腫瘤",
        "group_en": "Hematology and oncology",
        "findings": [
            ("recent_cancer_treatment", "Recent cancer treatment", "近期癌症治療"),
            ("known_cancer", "Known cancer", "已知癌症"),
            ("easy_bruising_bleeding", "Easy bruising or bleeding", "容易瘀青或出血"),
            ("bone_back_pain", "Bone or back pain", "骨痛或背痛"),
            (
                "bladder_bowel_dysfunction",
                "Bladder or bowel dysfunction",
                "膀胱或腸道功能改變",
            ),
            ("visual_disturbance", "Visual disturbance", "視覺異常"),
        ],
    },
]

DEFAULT_ASK_NEXT = [
    "先確認 ABC、生命徵象、血氧、意識狀態與是否需要急救處置。 / First confirm ABCs, vital signs, oxygen saturation, mental status, and need for emergency care.",
    "確認症狀開始時間、進展速度、最嚴重位置與是否有突然惡化。 / Clarify onset time, tempo, worst location, and sudden deterioration.",
    "確認懷孕可能、免疫低下、抗凝血藥、重大共病與近期手術或外傷。 / Check pregnancy possibility, immunocompromise, anticoagulants, major comorbidities, recent surgery, or trauma.",
    "依主要系統補問紅旗，再決定是否需要急診、影像、心電圖或實驗室檢查。 / Ask system-specific red flags, then decide on ED referral, imaging, ECG, or labs.",
]

CONDITIONS = [
    {
        "slug": "acute_coronary_syndrome",
        "name_zh": "急性冠心症",
        "name_en": "Acute coronary syndrome",
        "system": "Cardiovascular",
        "urgency": "emergent",
        "summary_zh": "胸痛合併呼吸困難、冒冷汗、手臂或下顎放射痛時需優先排除。",
        "summary_en": "Prioritize when chest pain occurs with dyspnea, diaphoresis, or arm/jaw radiation.",
        "signals": {
            "chest_pain": 4,
            "dyspnea": 2,
            "diaphoresis": 3,
            "radiating_arm_jaw_pain": 4,
            "hemodynamic_instability": 4,
            "syncope": 2,
        },
        "synonyms": ["heart attack", "myocardial infarction", "acs", "angina"],
        "ask_next": [
            "立即確認心電圖 ECG、血壓、血氧、疼痛開始時間與是否持續。 / Check ECG, blood pressure, oxygen saturation, onset time, and whether pain persists.",
            "補問冒冷汗、噁心、下顎或手臂放射痛、既往冠心病與危險因子。 / Ask about diaphoresis, nausea, jaw/arm radiation, CAD history, and risk factors.",
        ],
        "source_ids": ["aha_heart_attack", "nice_chest_pain"],
    },
    {
        "slug": "stroke_tia",
        "name_zh": "中風或短暫性腦缺血",
        "name_en": "Stroke or TIA",
        "system": "Neurologic",
        "urgency": "emergent",
        "summary_zh": "突發單側無力、言語或視覺改變、神經學缺損需立即處理。",
        "summary_en": "Sudden unilateral weakness, speech/vision changes, or focal deficit require urgent action.",
        "signals": {
            "neurologic_deficit": 4,
            "unilateral_weakness": 5,
            "speech_vision_changes": 5,
            "altered_mental_status": 2,
            "syncope": 1,
        },
        "synonyms": ["stroke", "tia", "cva", "mini stroke"],
        "ask_next": [
            "確認最後正常時間、FAST/BE-FAST 徵象、抗凝血藥與血糖。 / Confirm last-known-well time, FAST/BE-FAST signs, anticoagulants, and glucose.",
            "不要延誤急性中風流程；需要急診/中風團隊評估。 / Do not delay acute stroke pathway evaluation.",
        ],
        "source_ids": ["asa_stroke"],
    },
    {
        "slug": "sepsis",
        "name_zh": "敗血症",
        "name_en": "Sepsis",
        "system": "Infectious",
        "urgency": "emergent",
        "summary_zh": "感染表現合併意識改變、呼吸困難、低血壓或心搏過速時需優先排除。",
        "summary_en": "Suspect when infection features occur with confusion, dyspnea, hypotension, or tachycardia.",
        "signals": {
            "fever": 3,
            "hypothermia": 3,
            "altered_mental_status": 4,
            "tachycardia": 3,
            "dyspnea": 2,
            "hemodynamic_instability": 5,
            "immunocompromised": 2,
            "severe_pain": 1,
        },
        "synonyms": ["sepsis", "septic shock", "infection shock"],
        "ask_next": [
            "確認感染來源、血壓、呼吸頻率、尿量、乳酸與器官灌流狀態。 / Check infection source, blood pressure, respiratory rate, urine output, lactate, and perfusion.",
            "若不穩定，依急症流程處理，不等待完整鑑別列表。 / If unstable, follow emergency care pathways without waiting for a full list.",
        ],
        "source_ids": ["cdc_sepsis", "cdc_sepsis_signs"],
    },
    {
        "slug": "febrile_neutropenia",
        "name_zh": "發熱性嗜中性球低下",
        "name_en": "Febrile neutropenia",
        "system": "Hematology/Oncology/Infectious",
        "urgency": "emergent",
        "summary_zh": "近期癌症治療或免疫低下合併發燒時，需優先納入發熱性嗜中性球低下與感染風險。",
        "summary_en": "Prioritize when fever occurs after recent cancer therapy or with immunocompromise.",
        "signals": {
            "fever": 5,
            "recent_cancer_treatment": 4,
            "immunocompromised": 3,
            "altered_mental_status": 2,
            "hemodynamic_instability": 4,
        },
        "synonyms": ["febrile neutropenia", "neutropenic fever", "neutropenic sepsis"],
        "ask_next": [
            "確認最近化療/放療/免疫治療時間、最高體溫、ANC 或最近 CBC、感染灶、血壓與意識狀態。 / Clarify recent chemotherapy, radiation, or immunotherapy timing, maximum temperature, ANC or recent CBC, infection source, blood pressure, and mental status.",
        ],
        "source_ids": ["merck_neutropenia", "merck_professional"],
    },
    {
        "slug": "tumor_lysis_syndrome",
        "name_zh": "腫瘤溶解症候群",
        "name_en": "Tumor lysis syndrome",
        "system": "Hematology/Oncology/Metabolic",
        "urgency": "emergent",
        "summary_zh": "癌症治療後出現嘔吐、意識改變、脫水或循環不穩時，需想到腫瘤溶解造成的代謝異常。",
        "summary_en": "Consider after cancer therapy when vomiting, mental status change, dehydration, or instability suggests metabolic derangement.",
        "signals": {
            "recent_cancer_treatment": 5,
            "vomiting": 2,
            "altered_mental_status": 2,
            "extreme_thirst_polyuria": 1,
            "hemodynamic_instability": 2,
        },
        "synonyms": ["tumor lysis", "tumour lysis", "tls", "tumor lysis syndrome"],
        "ask_next": [
            "確認癌症類型與治療時間、腎功能、尿量、鉀磷鈣尿酸變化、心律或抽搐症狀。 / Clarify cancer type and treatment timing, renal function, urine output, potassium, phosphate, calcium, uric acid changes, rhythm, or seizure symptoms.",
        ],
        "source_ids": ["merck_cancer_therapy_adverse_effects", "merck_professional"],
    },
    {
        "slug": "metastatic_spinal_cord_compression",
        "name_zh": "轉移性脊髓壓迫",
        "name_en": "Metastatic spinal cord compression",
        "system": "Oncology/Neurologic",
        "urgency": "emergent",
        "summary_zh": "已知癌症合併背痛、骨痛、神經缺損或膀胱腸道功能改變時，需優先排除脊髓壓迫。",
        "summary_en": "Known cancer with back or bone pain, neurologic deficit, or bladder/bowel dysfunction requires urgent exclusion.",
        "signals": {
            "known_cancer": 5,
            "bone_back_pain": 4,
            "neurologic_deficit": 4,
            "unilateral_weakness": 3,
            "bladder_bowel_dysfunction": 5,
            "severe_pain": 2,
        },
        "synonyms": [
            "spinal cord compression",
            "mscc",
            "metastatic spinal cord compression",
        ],
        "ask_next": [
            "確認癌症史、背痛位置與進展、步態、肌力、感覺、反射、鞍區感覺與膀胱腸道功能。 / Clarify cancer history, back pain location and tempo, gait, strength, sensation, reflexes, saddle sensation, and bladder or bowel function.",
        ],
        "source_ids": ["nice_spinal_metastases_mscc", "merck_professional"],
    },
    {
        "slug": "hypercalcemia_of_malignancy",
        "name_zh": "惡性腫瘤相關高血鈣",
        "name_en": "Hypercalcemia of malignancy",
        "system": "Oncology/Metabolic",
        "urgency": "urgent",
        "summary_zh": "已知癌症合併意識改變、嘔吐、多渴多尿、脫水或虛弱時，需納入高血鈣相關風險。",
        "summary_en": "Known cancer with confusion, vomiting, thirst/polyuria, dehydration, or weakness should prompt hypercalcemia consideration.",
        "signals": {
            "known_cancer": 4,
            "altered_mental_status": 3,
            "vomiting": 2,
            "fatigue": 2,
            "extreme_thirst_polyuria": 2,
            "hemodynamic_instability": 2,
        },
        "synonyms": [
            "hypercalcemia of malignancy",
            "high calcium cancer",
            "hcm",
            "malignant hypercalcemia",
        ],
        "ask_next": [
            "確認癌症史、補充品或藥物、口渴多尿、便秘、意識狀態、脫水與近期鈣/腎功能數值。 / Clarify cancer history, supplements or medications, thirst/polyuria, constipation, mental status, dehydration, and recent calcium or renal values.",
        ],
        "source_ids": ["canadian_cancer_hypercalcemia", "merck_professional"],
    },
    {
        "slug": "acute_leukemia",
        "name_zh": "急性白血病",
        "name_en": "Acute leukemia",
        "system": "Hematology/Oncology",
        "urgency": "urgent",
        "summary_zh": "疲倦、發燒、容易瘀青出血、骨痛或體重減輕組合時，需納入急性白血病與血球異常。",
        "summary_en": "Fatigue, fever, easy bruising or bleeding, bone pain, or weight loss should include acute leukemia in the differential.",
        "signals": {
            "fatigue": 2,
            "fever": 2,
            "easy_bruising_bleeding": 5,
            "bone_back_pain": 3,
            "weight_loss": 2,
            "immunocompromised": 2,
        },
        "synonyms": ["acute leukemia", "all", "aml", "leukaemia", "leukemia"],
        "ask_next": [
            "確認瘀青出血、感染、骨痛、淋巴結或肝脾腫大、CBC 差異計數與周邊血抹片資訊。 / Clarify bruising or bleeding, infection, bone pain, lymph nodes or hepatosplenomegaly, CBC differential, and peripheral smear information.",
        ],
        "source_ids": ["merck_all", "merck_professional"],
    },
    {
        "slug": "pulmonary_embolism",
        "name_zh": "肺栓塞",
        "name_en": "Pulmonary embolism",
        "system": "Cardiopulmonary",
        "urgency": "emergent",
        "summary_zh": "呼吸困難、胸膜性胸痛、咳血、單側腿腫或心搏過速時需考慮。",
        "summary_en": "Consider with dyspnea, pleuritic pain, hemoptysis, unilateral leg swelling, or tachycardia.",
        "signals": {
            "dyspnea": 4,
            "pleuritic_pain": 3,
            "hemoptysis": 3,
            "unilateral_leg_swelling": 3,
            "tachycardia": 2,
            "chest_pain": 2,
            "hemodynamic_instability": 4,
        },
        "synonyms": ["pe", "pulmonary embolus", "embolism"],
        "ask_next": [
            "確認 VTE 風險、近期手術/臥床、癌症、懷孕、血氧與是否休克。 / Check VTE risks, recent surgery/immobility, cancer, pregnancy, oxygenation, and shock.",
        ],
        "source_ids": ["nice_chest_pain", "merck_professional"],
    },
    {
        "slug": "aortic_dissection",
        "name_zh": "主動脈剝離",
        "name_en": "Aortic dissection",
        "system": "Cardiovascular",
        "urgency": "emergent",
        "summary_zh": "撕裂樣胸背痛、神經症狀、昏厥或血流不穩需立即排除。",
        "summary_en": "Tearing chest/back pain with neurologic symptoms, syncope, or instability is high risk.",
        "signals": {
            "chest_pain": 3,
            "tearing_back_pain": 5,
            "syncope": 2,
            "neurologic_deficit": 2,
            "hemodynamic_instability": 4,
        },
        "synonyms": ["dissection", "aortic catastrophe"],
        "ask_next": [
            "確認疼痛是否突然、撕裂或移動，雙側血壓/脈搏差、神經缺損與馬凡特徵。 / Clarify sudden tearing/migrating pain, pulse/BP differential, neurologic deficits, and connective tissue risk.",
        ],
        "source_ids": ["nice_chest_pain", "merck_professional"],
    },
    {
        "slug": "meningitis",
        "name_zh": "腦膜炎",
        "name_en": "Meningitis",
        "system": "Neurologic/Infectious",
        "urgency": "emergent",
        "summary_zh": "發燒、頸部僵硬、意識改變或免疫低下合併頭痛時需考慮。",
        "summary_en": "Consider with fever, neck stiffness, altered mental status, or immunocompromise.",
        "signals": {
            "fever": 3,
            "neck_stiffness": 5,
            "altered_mental_status": 4,
            "immunocompromised": 2,
            "severe_pain": 1,
        },
        "synonyms": ["meningitis", "cns infection"],
        "ask_next": [
            "確認皮疹、光畏、免疫狀態、抗生素前血培與是否需要急診處置。 / Ask about rash, photophobia, immune status, cultures before antibiotics, and emergency care needs.",
        ],
        "source_ids": ["merck_headache_red_flags", "merck_professional"],
    },
    {
        "slug": "subarachnoid_hemorrhage",
        "name_zh": "蜘蛛膜下腔出血",
        "name_en": "Subarachnoid hemorrhage",
        "system": "Neurologic",
        "urgency": "emergent",
        "summary_zh": "雷擊樣頭痛或數秒內達最痛程度時必須優先排除。",
        "summary_en": "Thunderclap headache or maximal intensity within seconds is a must-not-miss pattern.",
        "signals": {
            "thunderclap_headache": 6,
            "neck_stiffness": 2,
            "altered_mental_status": 2,
            "neurologic_deficit": 2,
            "severe_pain": 2,
        },
        "synonyms": ["sah", "subarachnoid bleed", "thunderclap"],
        "ask_next": [
            "確認達峰時間、昏厥、頸部僵硬、抗凝血藥與神經缺損。 / Confirm time to peak, syncope, neck stiffness, anticoagulants, and neurologic deficits.",
        ],
        "source_ids": ["merck_headache_red_flags"],
    },
    {
        "slug": "appendicitis",
        "name_zh": "闌尾炎",
        "name_en": "Appendicitis",
        "system": "Abdominal",
        "urgency": "urgent",
        "summary_zh": "右下腹痛、發燒、嘔吐或反彈痛時需納入。",
        "summary_en": "Include with right lower quadrant pain, fever, vomiting, or peritoneal signs.",
        "signals": {
            "abdominal_pain": 2,
            "rlq_pain": 5,
            "fever": 2,
            "vomiting": 2,
            "rebound_guarding": 3,
        },
        "synonyms": ["appendix", "rlq"],
        "ask_next": [
            "確認疼痛移轉、食慾、反彈痛、防禦、懷孕可能與是否需影像/外科評估。 / Ask about migration, appetite, rebound/guarding, pregnancy possibility, imaging, and surgical evaluation.",
        ],
        "source_ids": ["nice_acute_abdomen"],
    },
    {
        "slug": "ectopic_pregnancy",
        "name_zh": "子宮外孕",
        "name_en": "Ectopic pregnancy",
        "system": "Obstetric/Gynecologic",
        "urgency": "emergent",
        "summary_zh": "可能懷孕者出現骨盆或腹痛、昏厥或血流不穩時不可漏掉。",
        "summary_en": "Must not miss in possible pregnancy with pelvic/abdominal pain, syncope, or instability.",
        "signals": {
            "pregnancy_possible": 5,
            "pelvic_pain": 4,
            "abdominal_pain": 2,
            "syncope": 3,
            "hemodynamic_instability": 4,
        },
        "synonyms": ["ectopic", "tubal pregnancy"],
        "ask_next": [
            "確認妊娠狀態、末次月經、陰道出血、暈厥與血流動力。 / Confirm pregnancy status, LMP, vaginal bleeding, syncope, and hemodynamics.",
        ],
        "source_ids": ["nice_acute_abdomen", "merck_professional"],
    },
    {
        "slug": "anaphylaxis",
        "name_zh": "過敏性休克",
        "name_en": "Anaphylaxis",
        "system": "Allergy/Emergency",
        "urgency": "emergent",
        "summary_zh": "臉唇舌腫、皮疹、呼吸窘迫或血流不穩需立即處置。",
        "summary_en": "Facial/lip/tongue swelling, rash, respiratory distress, or instability needs immediate action.",
        "signals": {
            "facial_lip_tongue_swelling": 5,
            "rash": 3,
            "respiratory_distress": 5,
            "wheeze": 2,
            "hemodynamic_instability": 4,
        },
        "synonyms": ["anaphylaxis", "allergic shock", "angioedema"],
        "ask_next": [
            "確認暴露物、氣道腫脹、喘鳴、血壓與是否需立即急救。 / Identify exposure, airway swelling, wheeze, blood pressure, and emergency treatment need.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "pneumonia",
        "name_zh": "肺炎",
        "name_en": "Pneumonia",
        "system": "Respiratory/Infectious",
        "urgency": "urgent",
        "summary_zh": "發燒、咳嗽痰、呼吸困難或低氧表現時需考慮。",
        "summary_en": "Consider with fever, cough/sputum, dyspnea, or hypoxemia features.",
        "signals": {"fever": 3, "cough_sputum": 4, "dyspnea": 3, "tachycardia": 1},
        "synonyms": ["pneumonia", "lung infection"],
        "ask_next": [
            "確認血氧、呼吸頻率、胸痛、痰性質、共病與是否需要影像。 / Check oxygenation, respiratory rate, chest pain, sputum, comorbidities, and imaging need.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "heart_failure_exacerbation",
        "name_zh": "心衰竭惡化",
        "name_en": "Heart failure exacerbation",
        "system": "Cardiovascular",
        "urgency": "urgent",
        "summary_zh": "呼吸困難合併端坐呼吸、水腫或胸痛時需考慮。",
        "summary_en": "Dyspnea with orthopnea, edema, or chest pain may reflect heart failure exacerbation.",
        "signals": {"dyspnea": 3, "orthopnea_edema": 5, "chest_pain": 1, "tachycardia": 1},
        "synonyms": ["heart failure", "chf", "pulmonary edema"],
        "ask_next": [
            "確認體重變化、端坐呼吸、下肢水腫、心臟病史、血氧與胸痛。 / Ask about weight change, orthopnea, edema, cardiac history, oxygenation, and chest pain.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "asthma_copd_exacerbation",
        "name_zh": "氣喘或 COPD 急性惡化",
        "name_en": "Asthma or COPD exacerbation",
        "system": "Respiratory",
        "urgency": "urgent",
        "summary_zh": "喘鳴、呼吸困難、咳嗽痰或呼吸窘迫時需納入。",
        "summary_en": "Wheeze, dyspnea, cough/sputum, or respiratory distress should trigger this pathway.",
        "signals": {"wheeze": 5, "dyspnea": 3, "cough_sputum": 2, "respiratory_distress": 4},
        "synonyms": ["asthma", "copd", "bronchospasm"],
        "ask_next": [
            "確認既往氣喘/COPD、吸入藥反應、血氧、說話能力與沉默胸。 / Check asthma/COPD history, inhaler response, oxygenation, speech ability, and silent chest.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "acute_angle_closure_glaucoma",
        "name_zh": "急性隅角閉鎖性青光眼",
        "name_en": "Acute angle-closure glaucoma",
        "system": "Ophthalmologic",
        "urgency": "emergent",
        "summary_zh": "眼痛、紅眼、頭痛、噁心或視覺改變時需急症處理。",
        "summary_en": "Eye pain/redness with headache, nausea, or vision change can be an emergency.",
        "signals": {"eye_pain_redness": 5, "severe_pain": 2, "vomiting": 1, "speech_vision_changes": 2},
        "synonyms": ["glaucoma", "acute glaucoma"],
        "ask_next": [
            "確認視力、瞳孔、眼壓風險、噁心嘔吐與是否需眼科急診。 / Check vision, pupil, IOP risk, nausea/vomiting, and urgent ophthalmology need.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "gi_bleed",
        "name_zh": "腸胃道出血",
        "name_en": "Gastrointestinal bleeding",
        "system": "Gastrointestinal",
        "urgency": "urgent",
        "summary_zh": "黑便、吐血、血便、昏厥或血流不穩時需優先評估。",
        "summary_en": "Melena, hematemesis, hematochezia, syncope, or instability requires prompt assessment.",
        "signals": {"gi_bleeding": 5, "syncope": 2, "hemodynamic_instability": 4, "abdominal_pain": 1},
        "synonyms": ["gi bleed", "melena", "hematemesis"],
        "ask_next": [
            "確認出血型態、量、抗凝血藥、血壓心跳、貧血症狀與肝病史。 / Clarify bleeding type/volume, anticoagulants, vitals, anemia symptoms, and liver disease.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "diabetic_ketoacidosis",
        "name_zh": "糖尿病酮酸中毒",
        "name_en": "Diabetic ketoacidosis",
        "system": "Metabolic",
        "urgency": "emergent",
        "summary_zh": "多渴多尿、嘔吐、腹痛、意識改變或呼吸異常時需考慮。",
        "summary_en": "Thirst/polyuria with vomiting, abdominal pain, altered mental status, or abnormal breathing is high risk.",
        "signals": {
            "extreme_thirst_polyuria": 4,
            "vomiting": 2,
            "abdominal_pain": 2,
            "altered_mental_status": 3,
            "respiratory_distress": 2,
        },
        "synonyms": ["dka", "ketoacidosis", "diabetic ketoacidosis"],
        "ask_next": [
            "確認血糖、酮體、脫水、感染誘因、胰島素中斷與意識狀態。 / Check glucose, ketones, dehydration, infection triggers, insulin omission, and mental status.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "hypoglycemia",
        "name_zh": "低血糖",
        "name_en": "Hypoglycemia",
        "system": "Metabolic",
        "urgency": "emergent",
        "summary_zh": "意識改變、昏厥、冒汗或低血糖風險者需立即確認血糖。",
        "summary_en": "Altered mental status, syncope, sweating, or hypoglycemia risk should trigger glucose check.",
        "signals": {"hypoglycemia_risk": 5, "altered_mental_status": 4, "syncope": 2, "diaphoresis": 2},
        "synonyms": ["low glucose", "low blood sugar", "hypoglycemia"],
        "ask_next": [
            "立即確認指尖血糖、糖尿病藥物、進食狀況與意識安全。 / Check point-of-care glucose, diabetes medications, intake, and mental status safety.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "temporal_arteritis",
        "name_zh": "巨細胞動脈炎",
        "name_en": "Giant cell arteritis",
        "system": "Vascular/Rheumatologic",
        "urgency": "urgent",
        "summary_zh": "50歲後新發頭痛、下顎跛行或視覺症狀時需優先排除。",
        "summary_en": "New headache after age 50 with jaw claudication or visual symptoms is high risk.",
        "signals": {
            "new_headache_after_50": 5,
            "jaw_claudication": 4,
            "speech_vision_changes": 2,
            "severe_pain": 1,
        },
        "synonyms": ["giant cell arteritis", "temporal arteritis", "gca"],
        "ask_next": [
            "確認年齡、顳部壓痛、下顎跛行、視覺症狀與近端肌痛。 / Confirm age, temporal tenderness, jaw claudication, visual symptoms, and proximal myalgia.",
        ],
        "source_ids": ["merck_headache_red_flags"],
    },
    {
        "slug": "pyelonephritis",
        "name_zh": "腎盂腎炎",
        "name_en": "Pyelonephritis",
        "system": "Urinary/Infectious",
        "urgency": "urgent",
        "summary_zh": "發燒、腰側痛與排尿症狀支持上泌尿道感染。",
        "summary_en": "Fever, flank pain, and urinary symptoms support upper urinary tract infection.",
        "signals": {"fever": 3, "flank_pain": 4, "dysuria": 3, "vomiting": 1, "pregnancy_possible": 1},
        "synonyms": ["kidney infection", "pyelo", "pyelonephritis"],
        "ask_next": [
            "確認發燒、腰側敲痛、排尿症狀、懷孕、敗血症徵象與嘔吐。 / Ask about fever, CVA tenderness, urinary symptoms, pregnancy, sepsis signs, and vomiting.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "biliary_disease",
        "name_zh": "膽道疾病或膽囊炎",
        "name_en": "Biliary disease or cholecystitis",
        "system": "Gastrointestinal",
        "urgency": "urgent",
        "summary_zh": "右上腹痛、飯後疼痛、發燒或黃疸時需考慮膽道疾病。",
        "summary_en": "RUQ pain, postprandial pain, fever, or jaundice suggests biliary pathology.",
        "signals": {"ruq_pain": 4, "postprandial_ruq_pain": 3, "fever": 2, "jaundice": 3, "vomiting": 1},
        "synonyms": ["cholecystitis", "cholangitis", "gallbladder", "biliary"],
        "ask_next": [
            "確認黃疸、發燒、Murphy sign、飯後痛、肝膽胰檢驗與是否感染。 / Check jaundice, fever, Murphy sign, postprandial pain, hepatobiliary labs, and infection.",
        ],
        "source_ids": ["nice_acute_abdomen", "merck_professional"],
    },
    {
        "slug": "viral_respiratory_infection",
        "name_zh": "病毒性呼吸道感染",
        "name_en": "Viral respiratory infection",
        "system": "Respiratory/Infectious",
        "urgency": "routine",
        "summary_zh": "咳嗽、發燒、疲倦但無不穩定或呼吸窘迫時列入常見原因。",
        "summary_en": "Common when cough, fever, and fatigue occur without instability or respiratory distress.",
        "signals": {"cough_sputum": 3, "fever": 2, "fatigue": 1},
        "synonyms": ["cold", "flu", "covid", "viral infection"],
        "ask_next": [
            "確認血氧、呼吸窘迫、免疫狀態、暴露史與需要檢測或隔離。 / Check oxygenation, distress, immune status, exposure, and testing/isolation needs.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "panic_anxiety",
        "name_zh": "恐慌或焦慮相關症狀",
        "name_en": "Panic or anxiety-related symptoms",
        "system": "Mental health",
        "urgency": "soon",
        "summary_zh": "在排除急性心肺、神經、代謝風險後，可納入焦慮或恐慌。",
        "summary_en": "Consider only after acute cardiopulmonary, neurologic, and metabolic risks are addressed.",
        "signals": {"dyspnea": 1, "chest_pain": 1, "tachycardia": 1, "diaphoresis": 1},
        "synonyms": ["panic", "anxiety", "panic attack"],
        "ask_next": [
            "先確認沒有 ACS、肺栓塞、低血糖、甲狀腺或物質相關風險。 / First rule out ACS, PE, hypoglycemia, thyroid, or substance-related risk.",
        ],
        "source_ids": ["nimh_panic_disorder", "nhs_panic_disorder"],
    },
    {
        "slug": "deep_vein_thrombosis",
        "name_zh": "深部靜脈栓塞",
        "name_en": "Deep vein thrombosis",
        "system": "Vascular",
        "urgency": "urgent",
        "summary_zh": "單側下肢腫脹或疼痛時需考慮，並評估肺栓塞風險。",
        "summary_en": "Consider with unilateral leg swelling or pain, and assess pulmonary embolism risk.",
        "signals": {"unilateral_leg_swelling": 5, "dyspnea": 1, "pleuritic_pain": 1},
        "synonyms": ["dvt", "deep vein thrombosis", "leg clot"],
        "ask_next": ["確認 VTE 風險、近期手術、臥床、癌症、懷孕與肺栓塞症狀。 / Check VTE risks, recent surgery, immobility, cancer, pregnancy, and PE symptoms."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "pneumothorax",
        "name_zh": "氣胸",
        "name_en": "Pneumothorax",
        "system": "Respiratory",
        "urgency": "emergent",
        "summary_zh": "突發胸痛或呼吸困難，尤其外傷或呼吸窘迫時需排除。",
        "summary_en": "Sudden chest pain or dyspnea, especially with trauma or distress, should prompt exclusion.",
        "signals": {"chest_pain": 3, "dyspnea": 4, "respiratory_distress": 4, "recent_trauma": 3},
        "synonyms": ["pneumothorax", "collapsed lung"],
        "ask_next": ["確認是否張力氣胸表現、外傷、血氧、呼吸音不對稱與血流不穩。 / Check tension features, trauma, oxygenation, asymmetric breath sounds, and instability."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "hypertensive_emergency",
        "name_zh": "高血壓急症",
        "name_en": "Hypertensive emergency",
        "system": "Cardiovascular",
        "urgency": "emergent",
        "summary_zh": "嚴重高血壓合併神經、胸痛、呼吸困難或腎功能風險時需急症評估。",
        "summary_en": "Severe hypertension with neurologic, chest, dyspnea, or kidney-risk features needs urgent evaluation.",
        "signals": {"neurologic_deficit": 2, "chest_pain": 2, "dyspnea": 2, "altered_mental_status": 3},
        "synonyms": ["hypertensive emergency", "malignant hypertension"],
        "ask_next": ["確認血壓數值、終端器官損傷症狀、用藥中斷與妊娠相關風險。 / Confirm BP, end-organ symptoms, medication interruption, and pregnancy-related risk."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "acute_pancreatitis",
        "name_zh": "急性胰臟炎",
        "name_en": "Acute pancreatitis",
        "system": "Gastrointestinal",
        "urgency": "urgent",
        "summary_zh": "上腹痛、嘔吐、膽道線索或酒精相關風險時需考慮。",
        "summary_en": "Consider with upper abdominal pain, vomiting, biliary clues, or alcohol-related risk.",
        "signals": {"abdominal_pain": 3, "vomiting": 3, "ruq_pain": 1, "severe_pain": 2},
        "synonyms": ["pancreatitis", "acute pancreatitis"],
        "ask_next": ["確認疼痛是否放射到背部、酒精、膽石、三酸甘油脂與脫水或休克。 / Ask about back radiation, alcohol, gallstones, triglycerides, dehydration, or shock."],
        "source_ids": ["merck_professional", "nice_acute_abdomen"],
    },
    {
        "slug": "bowel_obstruction",
        "name_zh": "腸阻塞",
        "name_en": "Bowel obstruction",
        "system": "Gastrointestinal",
        "urgency": "urgent",
        "summary_zh": "腹痛合併嘔吐、腹脹、停止排氣排便或手術史時需考慮。",
        "summary_en": "Abdominal pain with vomiting, distension, obstipation, or surgical history suggests obstruction.",
        "signals": {"abdominal_pain": 3, "vomiting": 3, "severe_pain": 1},
        "synonyms": ["bowel obstruction", "intestinal obstruction", "sbo"],
        "ask_next": ["確認腹脹、排氣排便、手術史、疝氣、發燒與腹膜刺激。 / Check distension, flatus/stool, surgery, hernia, fever, and peritoneal signs."],
        "source_ids": ["nice_acute_abdomen", "merck_professional"],
    },
    {
        "slug": "peritonitis",
        "name_zh": "腹膜炎或急腹症",
        "name_en": "Peritonitis or acute abdomen",
        "system": "Gastrointestinal",
        "urgency": "emergent",
        "summary_zh": "反彈痛、防禦、劇烈腹痛或血流不穩時需急症處理。",
        "summary_en": "Rebound, guarding, severe abdominal pain, or instability requires urgent action.",
        "signals": {"abdominal_pain": 3, "rebound_guarding": 6, "severe_pain": 2, "hemodynamic_instability": 4, "fever": 2},
        "synonyms": ["peritonitis", "acute abdomen", "surgical abdomen"],
        "ask_next": ["確認防禦、反彈痛、發燒、血流動力與是否需急診外科評估。 / Confirm guarding, rebound, fever, hemodynamics, and surgical emergency need."],
        "source_ids": ["nice_acute_abdomen"],
    },
    {
        "slug": "nephrolithiasis",
        "name_zh": "腎結石或輸尿管結石",
        "name_en": "Nephrolithiasis or ureteral stone",
        "system": "Urinary",
        "urgency": "soon",
        "summary_zh": "腰側絞痛、血尿或噁心嘔吐時列入，但需排除感染阻塞。",
        "summary_en": "Flank colic, hematuria, or vomiting suggests stone; exclude infected obstruction.",
        "signals": {"flank_pain": 5, "vomiting": 1, "dysuria": 1, "severe_pain": 2},
        "synonyms": ["kidney stone", "renal colic", "nephrolithiasis"],
        "ask_next": ["確認發燒、單腎、懷孕、尿量、血尿與感染徵象。 / Check fever, solitary kidney, pregnancy, urine output, hematuria, and infection signs."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "uncomplicated_uti",
        "name_zh": "下泌尿道感染",
        "name_en": "Lower urinary tract infection",
        "system": "Urinary",
        "urgency": "routine",
        "summary_zh": "排尿疼痛、頻尿或急尿但無發燒腰痛時可考慮。",
        "summary_en": "Dysuria, frequency, or urgency without fever/flank pain may fit lower UTI.",
        "signals": {"dysuria": 5, "fever": 1},
        "synonyms": ["uti", "cystitis", "urinary infection"],
        "ask_next": ["確認發燒、腰痛、懷孕、男性、免疫低下與反覆感染。 / Check fever, flank pain, pregnancy, male sex, immunocompromise, and recurrence."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "acute_urinary_retention",
        "name_zh": "急性尿滯留",
        "name_en": "Acute urinary retention",
        "system": "Urologic/Urinary",
        "urgency": "emergent",
        "summary_zh": "無法排尿、下腹脹痛或膀胱膨脹感時，需優先辨識急性尿滯留與阻塞風險。",
        "summary_en": "Inability to void with lower abdominal pain, distention, or bladder fullness should prioritize acute urinary retention.",
        "signals": {
            "inability_to_void": 6,
            "abdominal_pain": 2,
            "severe_pain": 2,
            "dysuria": 1,
            "neurologic_deficit": 1,
        },
        "synonyms": [
            "urinary retention",
            "acute urinary retention",
            "unable to urinate",
            "cannot void",
        ],
        "ask_next": [
            "確認最後排尿時間、下腹膨脹/疼痛、尿量、前列腺或神經病史、近期手術/麻醉、抗膽鹼或鴉片類藥物。 / Clarify last void, suprapubic distention or pain, urine output, prostate or neurologic history, recent surgery or anesthesia, and anticholinergic or opioid exposure.",
        ],
        "source_ids": ["merck_urinary_retention", "niddk_urinary_retention"],
    },
    {
        "slug": "gastroenteritis",
        "name_zh": "腸胃炎",
        "name_en": "Gastroenteritis",
        "system": "Gastrointestinal/Infectious",
        "urgency": "routine",
        "summary_zh": "嘔吐、腹痛、發燒或群聚暴露時列入常見原因。",
        "summary_en": "Vomiting, abdominal pain, fever, or exposure clusters can suggest gastroenteritis.",
        "signals": {"vomiting": 4, "abdominal_pain": 2, "fever": 1},
        "synonyms": ["gastroenteritis", "stomach flu", "food poisoning"],
        "ask_next": ["確認脫水、血便、免疫低下、旅遊、食物暴露與腹膜刺激。 / Check dehydration, bloody stool, immunocompromise, travel, food exposure, and peritoneal signs."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "migraine",
        "name_zh": "偏頭痛",
        "name_en": "Migraine",
        "system": "Neurologic",
        "urgency": "routine",
        "summary_zh": "反覆頭痛合併噁心、畏光或類似既往型態時可考慮；需先排除紅旗。",
        "summary_en": "Recurrent headache with nausea, photophobia, or prior pattern can fit migraine after red flags are excluded.",
        "signals": {"vomiting": 1, "severe_pain": 1},
        "synonyms": ["migraine", "migraine headache"],
        "ask_next": ["先確認雷擊樣頭痛、神經缺損、發燒、頸僵硬、外傷與50歲後新發。 / First check thunderclap, neurologic deficit, fever, neck stiffness, trauma, and new headache after 50."],
        "source_ids": ["merck_headache_red_flags", "merck_professional"],
    },
    {
        "slug": "tension_type_headache",
        "name_zh": "緊縮型頭痛",
        "name_en": "Tension-type headache",
        "system": "Neurologic",
        "urgency": "routine",
        "summary_zh": "雙側壓迫感、非突發且無紅旗時可考慮。",
        "summary_en": "Bilateral pressure-like headache without sudden onset or red flags can fit this pattern.",
        "signals": {"severe_pain": 1, "fatigue": 1},
        "synonyms": ["tension headache", "tension-type headache"],
        "ask_next": ["確認沒有紅旗、藥物過度使用、視覺症狀或感染線索。 / Confirm no red flags, medication overuse, visual symptoms, or infection clues."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "intracranial_mass",
        "name_zh": "顱內腫瘤或佔位病灶",
        "name_en": "Intracranial mass lesion",
        "system": "Neurologic",
        "urgency": "urgent",
        "summary_zh": "癌症史、免疫低下、神經缺損或50歲後新發頭痛時需考慮。",
        "summary_en": "Cancer history, immunocompromise, neurologic deficit, or new headache after 50 raises concern.",
        "signals": {"new_headache_after_50": 3, "neurologic_deficit": 3, "immunocompromised": 2, "altered_mental_status": 2},
        "synonyms": ["brain tumor", "intracranial mass", "metastasis"],
        "ask_next": ["確認癌症史、癲癇、晨間嘔吐、進行性惡化與神經缺損。 / Ask about cancer, seizure, morning vomiting, progression, and neurologic deficits."],
        "source_ids": ["merck_headache_red_flags", "merck_professional"],
    },
    {
        "slug": "concussion",
        "name_zh": "腦震盪或輕度腦外傷",
        "name_en": "Concussion or mild traumatic brain injury",
        "system": "Trauma/Neurologic",
        "urgency": "soon",
        "summary_zh": "近期頭部外傷後頭痛、暈眩、嘔吐或意識改變需評估。",
        "summary_en": "Headache, dizziness, vomiting, or mental status change after head trauma needs assessment.",
        "signals": {"recent_trauma": 5, "vomiting": 1, "altered_mental_status": 3, "severe_pain": 1},
        "synonyms": ["concussion", "mild tbi", "head injury"],
        "ask_next": ["確認失去意識、抗凝血藥、反覆嘔吐、神經缺損與頭痛惡化。 / Check loss of consciousness, anticoagulants, repeated vomiting, deficits, and worsening headache."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "thyroid_storm",
        "name_zh": "甲狀腺風暴",
        "name_en": "Thyroid storm",
        "system": "Endocrine",
        "urgency": "emergent",
        "summary_zh": "發燒、心搏過速、意識改變或嚴重全身症狀時需考慮。",
        "summary_en": "Fever, tachycardia, altered mental status, or severe systemic illness can suggest thyroid storm.",
        "signals": {"fever": 2, "tachycardia": 4, "altered_mental_status": 3, "diaphoresis": 1},
        "synonyms": ["thyroid storm", "thyrotoxicosis crisis"],
        "ask_next": ["確認甲亢病史、誘發感染、體溫、心律、腸胃症狀與意識。 / Check hyperthyroidism history, infection trigger, temperature, rhythm, GI symptoms, and mentation."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "hypothyroidism",
        "name_zh": "甲狀腺低下",
        "name_en": "Hypothyroidism",
        "system": "Endocrine",
        "urgency": "routine",
        "summary_zh": "疲倦、體重變化、怕冷或心搏慢等慢性表現時可納入。",
        "summary_en": "Fatigue, weight change, cold intolerance, or bradycardic chronic presentations may fit.",
        "signals": {"fatigue": 2, "weight_loss": 1},
        "synonyms": ["hypothyroid", "hypothyroidism", "myxedema"],
        "ask_next": ["確認症狀時間軸、藥物、甲狀腺病史與是否有低體溫或意識改變。 / Check timeline, medications, thyroid history, hypothermia, and mental status."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "adrenal_crisis",
        "name_zh": "腎上腺危象",
        "name_en": "Adrenal crisis",
        "system": "Endocrine",
        "urgency": "emergent",
        "summary_zh": "血流不穩、嘔吐、腹痛、疲倦或類固醇中斷時需考慮。",
        "summary_en": "Instability, vomiting, abdominal pain, fatigue, or steroid interruption can suggest adrenal crisis.",
        "signals": {"hemodynamic_instability": 4, "vomiting": 2, "abdominal_pain": 2, "fatigue": 1},
        "synonyms": ["adrenal crisis", "adrenal insufficiency"],
        "ask_next": ["確認類固醇使用、中斷、感染壓力、低血壓、低血糖與電解質。 / Check steroid use/cessation, infection stress, hypotension, hypoglycemia, and electrolytes."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "anemia",
        "name_zh": "貧血",
        "name_en": "Anemia",
        "system": "Hematologic",
        "urgency": "soon",
        "summary_zh": "疲倦、呼吸困難、昏厥或腸胃道出血線索時可納入。",
        "summary_en": "Fatigue, dyspnea, syncope, or GI bleeding clues can suggest anemia.",
        "signals": {"fatigue": 3, "dyspnea": 1, "syncope": 1, "gi_bleeding": 3},
        "synonyms": ["anemia", "anaemia", "low hemoglobin"],
        "ask_next": ["確認出血、月經、黑便、營養、慢性病、心肺症狀與 CBC。 / Ask about bleeding, menses, melena, nutrition, chronic disease, cardiopulmonary symptoms, and CBC."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "malignancy_red_flag",
        "name_zh": "惡性腫瘤警訊",
        "name_en": "Malignancy red-flag pattern",
        "system": "Oncology",
        "urgency": "soon",
        "summary_zh": "非預期體重減輕、疲倦、夜間症狀或局部持續症狀需安排評估。",
        "summary_en": "Unintentional weight loss, fatigue, night symptoms, or persistent focal symptoms need evaluation.",
        "signals": {"weight_loss": 5, "fatigue": 1, "new_headache_after_50": 1},
        "synonyms": ["cancer", "malignancy", "weight loss"],
        "ask_next": ["確認體重減輕幅度、夜汗、發燒、出血、局部症狀與篩檢史。 / Check amount of weight loss, night sweats, fever, bleeding, focal symptoms, and screening history."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "acute_psychosis",
        "name_zh": "急性精神病性症狀",
        "name_en": "Acute psychosis",
        "system": "Mental health/Neurologic",
        "urgency": "urgent",
        "summary_zh": "幻覺、妄想、思考或行為混亂、嚴重激動或新發精神病性症狀時需納入。",
        "summary_en": "Hallucinations, delusions, disorganized thinking or behavior, severe agitation, or new psychotic symptoms should be included.",
        "signals": {
            "hallucinations_delusions": 5,
            "severe_agitation": 3,
            "altered_mental_status": 2,
            "substance_use_concern": 1,
            "suicidal_ideation": 1,
            "self_harm_behavior": 1,
        },
        "synonyms": [
            "acute psychosis",
            "first episode psychosis",
            "psychosis",
            "hallucinations",
            "delusions",
        ],
        "ask_next": [
            "確認起始時間、幻覺/妄想內容、思考或行為混亂、激動程度、物質或藥物暴露、譫妄/神經/內分泌等醫療原因與自傷/傷人安全風險。 / Clarify onset, hallucination or delusion content, disorganized thought or behavior, agitation, substance or medication exposure, delirium, neurologic, endocrine or other medical causes, and self-harm or violence safety risk.",
        ],
        "source_ids": [
            "nice_psychosis",
            "camh_psychosis_screening",
            "merck_psychosis_medical_condition",
        ],
    },
    {
        "slug": "mania_or_hypomania",
        "name_zh": "躁症或輕躁症發作",
        "name_en": "Mania or hypomania",
        "system": "Mental health",
        "urgency": "urgent",
        "summary_zh": "睡眠需求降低、活動量或語速增加、衝動高風險行為或精神病性症狀時需納入。",
        "summary_en": "Decreased need for sleep, increased activity or pressured speech, risky impulsive behavior, or psychotic symptoms should include mania or hypomania.",
        "signals": {
            "decreased_need_for_sleep": 5,
            "risky_impulsive_behavior": 5,
            "severe_agitation": 2,
            "hallucinations_delusions": 2,
            "substance_use_concern": 1,
            "suicidal_ideation": 1,
        },
        "synonyms": [
            "mania",
            "hypomania",
            "manic episode",
            "bipolar mania",
            "bipolar disorder",
        ],
        "ask_next": [
            "確認睡眠需求、精力/活動量、語速或思緒奔逸、誇大、衝動風險行為、精神病性症狀、物質/藥物誘發與立即安全風險。 / Clarify sleep need, energy or activity, pressured speech or racing thoughts, grandiosity, risky impulsive behavior, psychotic symptoms, substance or medication triggers, and immediate safety risk.",
        ],
        "source_ids": ["nice_bipolar", "merck_bipolar"],
    },
    {
        "slug": "eating_disorder_medical_risk",
        "name_zh": "飲食障礙與醫療風險",
        "name_en": "Eating disorder with medical risk",
        "system": "Mental health/Metabolic",
        "urgency": "urgent",
        "summary_zh": "限制飲食、體重恐懼、暴食或清除行為合併體重下降、昏厥、低血糖或嘔吐時需納入。",
        "summary_en": "Restrictive eating, weight fear, bingeing, or purging with weight loss, syncope, hypoglycemia, or vomiting should be included.",
        "signals": {
            "restrictive_eating_or_weight_fear": 5,
            "purging_behavior": 5,
            "binge_eating_loss_of_control": 3,
            "weight_loss": 4,
            "vomiting": 2,
            "syncope": 3,
            "hypoglycemia_risk": 3,
            "fatigue": 1,
        },
        "synonyms": [
            "eating disorder",
            "anorexia nervosa",
            "bulimia nervosa",
            "binge eating disorder",
            "purging",
        ],
        "ask_next": [
            "確認限制飲食、暴食/清除行為、體重變化、昏厥/心悸、嘔吐或瀉藥/利尿劑使用、低血糖或電解質風險、自傷風險與是否有醫療不穩定。 / Clarify restriction, bingeing or purging, weight trajectory, syncope or palpitations, vomiting or laxative/diuretic use, hypoglycemia or electrolyte risk, self-harm risk, and medical instability.",
        ],
        "source_ids": [
            "nimh_eating_disorders",
            "merck_anorexia_nervosa",
            "merck_bulimia_nervosa",
        ],
    },
    {
        "slug": "depression",
        "name_zh": "憂鬱症狀",
        "name_en": "Depressive symptoms",
        "system": "Mental health",
        "urgency": "soon",
        "summary_zh": "疲倦、睡眠或食慾改變、情緒低落時可納入；需主動評估自傷風險。",
        "summary_en": "Low mood with fatigue, sleep, or appetite change can fit; screen for self-harm risk.",
        "signals": {"fatigue": 2, "weight_loss": 1},
        "synonyms": ["depression", "depressive symptoms", "low mood"],
        "ask_next": ["確認自殺意念、自傷計畫、精神病症狀、物質使用與支持系統。 / Check suicidal ideation, self-harm plan, psychosis, substances, and supports."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "suicide_self_harm_risk",
        "name_zh": "自殺或自傷風險",
        "name_en": "Suicide or self-harm risk",
        "system": "Mental health/Emergency",
        "urgency": "emergent",
        "summary_zh": "任何自殺意念、計畫、近期自傷或安全疑慮都需立即安全評估。",
        "summary_en": "Any suicidal ideation, plan, recent self-harm, or safety concern requires immediate safety assessment.",
        "signals": {
            "suicidal_ideation": 6,
            "self_harm_behavior": 6,
            "severe_agitation": 2,
            "substance_use_concern": 1,
            "altered_mental_status": 1,
        },
        "synonyms": ["suicide risk", "self harm", "suicidal ideation", "self-harm"],
        "ask_next": ["直接詢問意念、計畫、手段、時間、保護因子與是否需要立即安全處置。 / Ask directly about ideation, plan, means, timing, protective factors, and immediate safety needs."],
        "source_ids": ["nimh_suicide_warning_signs", "merck_professional"],
    },
    {
        "slug": "delirium",
        "name_zh": "譫妄",
        "name_en": "Delirium",
        "system": "Neurologic",
        "urgency": "urgent",
        "summary_zh": "急性意識或注意力波動需找感染、代謝、藥物或中樞病因。",
        "summary_en": "Acute fluctuating attention or consciousness requires evaluation for infection, metabolic, medication, or CNS causes.",
        "signals": {"altered_mental_status": 5, "fever": 1, "hypoglycemia_risk": 1},
        "synonyms": ["delirium", "acute confusion"],
        "ask_next": ["確認基準認知、急性時間軸、感染、藥物、疼痛、尿滯留、低氧與血糖。 / Check baseline cognition, acute timeline, infection, medications, pain, retention, hypoxia, and glucose."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "medication_toxicity",
        "name_zh": "藥物或毒物中毒",
        "name_en": "Medication or toxic ingestion",
        "system": "Toxicology",
        "urgency": "emergent",
        "summary_zh": "意識改變、昏厥、心搏過速、嘔吐或自傷疑慮時需詢問暴露。",
        "summary_en": "Altered mental status, syncope, tachycardia, vomiting, or self-harm concern should prompt exposure history.",
        "signals": {"altered_mental_status": 4, "syncope": 2, "tachycardia": 2, "vomiting": 1},
        "synonyms": ["overdose", "toxicity", "poisoning", "ingestion"],
        "ask_next": ["確認藥物清單、劑量、時間、意圖、共同攝入、心電圖與毒物中心。 / Check medication list, dose, timing, intent, co-ingestions, ECG, and poison control."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "serotonin_syndrome",
        "name_zh": "血清素症候群",
        "name_en": "Serotonin syndrome",
        "system": "Toxicology/Neurologic",
        "urgency": "emergent",
        "summary_zh": "發燒、心搏過速、意識改變、冒汗或相關藥物暴露時需考慮。",
        "summary_en": "Fever, tachycardia, altered mental status, diaphoresis, or serotonergic exposure suggests risk.",
        "signals": {"fever": 2, "tachycardia": 3, "altered_mental_status": 3, "diaphoresis": 2},
        "synonyms": ["serotonin syndrome", "ssri toxicity"],
        "ask_next": ["確認 SSRI/SNRI/MAOI、止痛藥、娛樂用藥、肌陣攣、反射亢進與體溫。 / Check serotonergic drugs, analgesics, recreational drugs, clonus, hyperreflexia, and temperature."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "heat_stroke",
        "name_zh": "熱中暑",
        "name_en": "Heat stroke",
        "system": "Environmental",
        "urgency": "emergent",
        "summary_zh": "高溫暴露合併意識改變、發燒或血流不穩需立即處理。",
        "summary_en": "Heat exposure with altered mental status, hyperthermia, or instability is an emergency.",
        "signals": {"fever": 3, "altered_mental_status": 4, "hemodynamic_instability": 3},
        "synonyms": ["heat stroke", "hyperthermia", "heat illness"],
        "ask_next": ["確認環境暴露、核心體溫、意識、脫水、橫紋肌溶解與立即降溫。 / Check exposure, core temperature, mental status, dehydration, rhabdomyolysis, and cooling need."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "hypothermia",
        "name_zh": "低體溫症",
        "name_en": "Hypothermia",
        "system": "Environmental",
        "urgency": "emergent",
        "summary_zh": "低溫暴露或低體溫合併意識改變、心律或血流問題時需急症處理。",
        "summary_en": "Cold exposure or hypothermia with mental status, rhythm, or hemodynamic issues is high risk.",
        "signals": {"hypothermia": 5, "altered_mental_status": 3, "hemodynamic_instability": 2},
        "synonyms": ["hypothermia", "cold exposure"],
        "ask_next": ["確認核心體溫、暴露時間、心律、血糖、外傷與復溫安全。 / Check core temperature, exposure duration, rhythm, glucose, trauma, and rewarming safety."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "cellulitis",
        "name_zh": "蜂窩性組織炎",
        "name_en": "Cellulitis",
        "system": "Skin/Infectious",
        "urgency": "soon",
        "summary_zh": "皮膚紅腫熱痛合併發燒或免疫低下時需評估感染嚴重度。",
        "summary_en": "Skin erythema, warmth, swelling, and pain with fever or immunocompromise needs severity assessment.",
        "signals": {"rash": 3, "fever": 2, "immunocompromised": 2},
        "synonyms": ["cellulitis", "skin infection"],
        "ask_next": ["確認範圍擴大、疼痛程度、膿瘍、糖尿病、免疫低下與壞死感染紅旗。 / Check spread, pain severity, abscess, diabetes, immunocompromise, and necrotizing red flags."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "necrotizing_soft_tissue_infection",
        "name_zh": "壞死性軟組織感染",
        "name_en": "Necrotizing soft tissue infection",
        "system": "Skin/Infectious",
        "urgency": "emergent",
        "summary_zh": "劇痛、血流不穩、發燒或快速惡化皮膚感染需立即排除。",
        "summary_en": "Severe pain, instability, fever, or rapidly worsening skin infection must be excluded.",
        "signals": {"severe_pain": 4, "fever": 3, "hemodynamic_instability": 4, "rash": 2, "immunocompromised": 1},
        "synonyms": ["necrotizing fasciitis", "nsti", "flesh eating"],
        "ask_next": ["確認疼痛是否超出外觀、快速擴大、水泡、皮膚壞死、休克與外科急症需求。 / Check pain out of proportion, rapid spread, bullae, necrosis, shock, and surgical emergency need."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "skin_abscess",
        "name_zh": "皮膚或軟組織膿瘍",
        "name_en": "Skin or soft tissue abscess",
        "system": "Skin/Soft tissue/Infectious",
        "urgency": "soon",
        "summary_zh": "局部化膿、紅腫熱痛、壓痛或發燒時需與蜂窩性組織炎及深部感染區分。",
        "summary_en": "Purulence, localized warmth, swelling, tenderness, or fever should distinguish abscess from cellulitis or deeper infection.",
        "signals": {
            "purulent_skin_lesion": 5,
            "rash": 2,
            "fever": 2,
            "severe_pain": 1,
            "immunocompromised": 1,
            "rapidly_spreading_skin_infection": 1,
        },
        "synonyms": [
            "skin abscess",
            "cutaneous abscess",
            "soft tissue abscess",
            "boil",
            "furuncle",
        ],
        "ask_next": [
            "確認是否有膿液或波動感、紅腫熱痛範圍、發燒、免疫低下、快速擴大、深部位置與是否需程序或影像評估。 / Clarify purulence or fluctuance, erythema/warmth/tenderness extent, fever, immunocompromise, rapid spread, deep location, and need for procedural or imaging evaluation.",
        ],
        "source_ids": ["merck_abscesses", "idsa_ssti_guideline"],
    },
    {
        "slug": "herpes_zoster",
        "name_zh": "帶狀疱疹",
        "name_en": "Herpes zoster (shingles)",
        "system": "Skin/Neurologic/Infectious",
        "urgency": "urgent",
        "summary_zh": "疼痛、刺痛或搔癢後出現單側皮節水泡疹，尤其眼部或免疫低下者需優先辨識。",
        "summary_en": "Pain, tingling, or itching followed by unilateral dermatomal vesicles should identify herpes zoster, especially with eye involvement or immunocompromise.",
        "signals": {
            "vesicular_dermatomal_rash": 6,
            "severe_pain": 2,
            "rash": 2,
            "eye_pain_redness": 4,
            "immunocompromised": 2,
        },
        "synonyms": [
            "shingles",
            "herpes zoster",
            "zoster",
            "dermatomal vesicular rash",
        ],
        "ask_next": [
            "確認皮疹是否沿單側皮節、疼痛/刺痛先於皮疹、眼耳受侵犯、免疫低下、散播性皮疹與神經併發症線索。 / Clarify unilateral dermatomal distribution, pain or tingling before rash, eye or ear involvement, immunocompromise, disseminated rash, and neurologic complication clues.",
        ],
        "source_ids": [
            "cdc_shingles_clinical_features",
            "cdc_shingles_clinical_overview",
        ],
    },
    {
        "slug": "stevens_johnson_syndrome_ten",
        "name_zh": "史蒂文斯-強森症候群 / 毒性表皮壞死溶解症",
        "name_en": "Stevens-Johnson syndrome / toxic epidermal necrolysis",
        "system": "Skin/Soft tissue/Toxicology",
        "urgency": "emergent",
        "summary_zh": "新用藥後發燒、皮疹快速擴大、黏膜病灶、皮膚水泡或脫落時需立即排除。",
        "summary_en": "Fever, rapidly spreading rash, mucosal lesions, blistering, or sloughing after medication exposure must raise SJS/TEN concern.",
        "signals": {
            "mucosal_lesions": 6,
            "skin_sloughing_or_blistering": 6,
            "new_medication_exposure": 4,
            "rash": 4,
            "fever": 3,
            "severe_pain": 2,
            "eye_pain_redness": 1,
        },
        "synonyms": [
            "stevens-johnson syndrome",
            "sjs",
            "toxic epidermal necrolysis",
            "ten",
            "sjs ten",
        ],
        "ask_next": [
            "確認近期新藥或高風險藥物、發燒、皮疹擴大速度、口眼生殖器黏膜病灶、皮膚水泡/脫落、疼痛、體表面積與血流動力。 / Clarify recent new or high-risk medications, fever, rash spread, oral/ocular/genital mucosal lesions, blistering or sloughing, pain, body surface area, and hemodynamics.",
        ],
        "source_ids": ["merck_sjs_ten", "dermnet_sjs_ten"],
    },
    {
        "slug": "acute_liver_failure",
        "name_zh": "急性肝衰竭",
        "name_en": "Acute liver failure",
        "system": "Hepatic",
        "urgency": "emergent",
        "summary_zh": "黃疸合併意識改變、出血或毒物/藥物暴露需急症評估。",
        "summary_en": "Jaundice with altered mental status, bleeding, or toxic/medication exposure is high risk.",
        "signals": {"jaundice": 4, "altered_mental_status": 4, "vomiting": 1},
        "synonyms": ["acute liver failure", "hepatic failure"],
        "ask_next": ["確認乙醯胺酚、病毒性肝炎、酒精、凝血、低血糖與腦病變。 / Check acetaminophen, viral hepatitis, alcohol, coagulation, hypoglycemia, and encephalopathy."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "acute_kidney_injury",
        "name_zh": "急性腎損傷",
        "name_en": "Acute kidney injury",
        "system": "Renal",
        "urgency": "urgent",
        "summary_zh": "尿量下降、脫水、感染、藥物或阻塞線索時需考慮。",
        "summary_en": "Reduced urine output, dehydration, infection, medications, or obstruction clues can suggest AKI.",
        "signals": {"hemodynamic_instability": 2, "dysuria": 1, "flank_pain": 1, "vomiting": 1},
        "synonyms": ["aki", "acute kidney injury", "renal failure"],
        "ask_next": ["確認尿量、腎毒性藥物、脫水、感染、阻塞、電解質與肌酸酐。 / Check urine output, nephrotoxins, dehydration, infection, obstruction, electrolytes, and creatinine."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "covid_influenza",
        "name_zh": "COVID-19 或流感樣疾病",
        "name_en": "COVID-19 or influenza-like illness",
        "system": "Respiratory/Infectious",
        "urgency": "soon",
        "summary_zh": "發燒、咳嗽、疲倦或呼吸症狀時列入，但需看低氧與高風險族群。",
        "summary_en": "Fever, cough, fatigue, or respiratory symptoms fit; assess oxygenation and high-risk status.",
        "signals": {"fever": 3, "cough_sputum": 3, "fatigue": 2, "dyspnea": 1},
        "synonyms": ["covid", "influenza", "flu", "ili"],
        "ask_next": ["確認暴露、疫苗、高風險共病、血氧、呼吸窘迫與檢測時機。 / Check exposure, vaccination, high-risk comorbidities, oxygenation, distress, and testing timing."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "tuberculosis",
        "name_zh": "結核病",
        "name_en": "Tuberculosis",
        "system": "Respiratory/Infectious",
        "urgency": "soon",
        "summary_zh": "慢性咳嗽、體重減輕、發燒或免疫低下時需納入。",
        "summary_en": "Chronic cough, weight loss, fever, or immunocompromise should prompt consideration.",
        "signals": {"cough_sputum": 2, "weight_loss": 4, "fever": 2, "immunocompromised": 2},
        "synonyms": ["tb", "tuberculosis"],
        "ask_next": ["確認咳嗽時間、夜汗、接觸史、旅居、免疫狀態與感染管制需求。 / Check cough duration, night sweats, contacts, travel/residence, immune status, and infection control."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "peptic_ulcer_disease",
        "name_zh": "消化性潰瘍",
        "name_en": "Peptic ulcer disease",
        "system": "Gastrointestinal",
        "urgency": "soon",
        "summary_zh": "上腹痛、腸胃道出血、NSAID 或幽門螺旋桿菌風險時可納入。",
        "summary_en": "Epigastric pain, GI bleeding, NSAID exposure, or H. pylori risk can fit.",
        "signals": {"abdominal_pain": 2, "gi_bleeding": 3, "vomiting": 1},
        "synonyms": ["peptic ulcer", "pud", "gastric ulcer", "duodenal ulcer"],
        "ask_next": ["確認黑便、吐血、NSAID、抗凝血藥、體重減輕與穿孔紅旗。 / Check melena, hematemesis, NSAIDs, anticoagulants, weight loss, and perforation red flags."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "gerd",
        "name_zh": "胃食道逆流",
        "name_en": "Gastroesophageal reflux disease",
        "system": "Gastrointestinal",
        "urgency": "routine",
        "summary_zh": "胸口灼熱或飯後/躺下惡化可納入，但需先排除心肺紅旗。",
        "summary_en": "Heartburn or postprandial/recumbent worsening can fit after cardiopulmonary red flags are excluded.",
        "signals": {"chest_pain": 1, "abdominal_pain": 1},
        "synonyms": ["gerd", "reflux", "heartburn"],
        "ask_next": ["先確認 ACS 紅旗；再問吞嚥困難、體重減輕、出血、夜間症狀與藥物。 / First check ACS red flags; then ask dysphagia, weight loss, bleeding, nocturnal symptoms, and medications."],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "pelvic_inflammatory_disease",
        "name_zh": "骨盆腔發炎性疾病",
        "name_en": "Pelvic inflammatory disease",
        "system": "Gynecologic/Infectious",
        "urgency": "urgent",
        "summary_zh": "骨盆或下腹痛合併發燒、陰道分泌物、不規則出血或子宮頸移動痛時需納入。",
        "summary_en": "Pelvic or lower abdominal pain with fever, discharge, irregular bleeding, or cervical motion tenderness should include PID.",
        "signals": {
            "pelvic_pain": 5,
            "fever": 2,
            "vaginal_discharge": 4,
            "cervical_motion_tenderness": 5,
            "vaginal_bleeding": 1,
            "dysuria": 1,
            "pregnancy_possible": 1,
        },
        "synonyms": [
            "pelvic inflammatory disease",
            "pid",
            "salpingitis",
            "endometritis",
        ],
        "ask_next": [
            "確認下腹/骨盆痛、發燒、陰道分泌物或不規則出血、子宮頸移動痛/子宮或附件壓痛、懷孕可能與是否排除外科急症。 / Clarify lower abdominal or pelvic pain, fever, discharge or irregular bleeding, cervical motion, uterine or adnexal tenderness, pregnancy possibility, and whether surgical emergencies are excluded.",
        ],
        "source_ids": ["merck_pid", "cdc_pid"],
    },
    {
        "slug": "tubo_ovarian_abscess",
        "name_zh": "輸卵管卵巢膿瘍",
        "name_en": "Tubo-ovarian abscess",
        "system": "Gynecologic/Infectious",
        "urgency": "emergent",
        "summary_zh": "骨盆痛合併發燒、劇痛、嘔吐、陰道分泌物或血流不穩時需優先排除。",
        "summary_en": "Pelvic pain with fever, severe pain, vomiting, discharge, or instability should prioritize tubo-ovarian abscess.",
        "signals": {
            "pelvic_pain": 5,
            "fever": 4,
            "vaginal_discharge": 3,
            "cervical_motion_tenderness": 4,
            "severe_pain": 2,
            "vomiting": 2,
            "hemodynamic_instability": 4,
            "pregnancy_possible": 1,
        },
        "synonyms": [
            "tubo-ovarian abscess",
            "tubo ovarian abscess",
            "toa",
            "adnexal abscess",
        ],
        "ask_next": [
            "確認發燒高度、毒性外觀、單側或雙側骨盆痛、分泌物、嘔吐、腹膜刺激、妊娠狀態與是否需要急症婦科/影像評估。 / Clarify fever severity, toxic appearance, unilateral or bilateral pelvic pain, discharge, vomiting, peritoneal signs, pregnancy status, and need for urgent gynecologic or imaging evaluation.",
        ],
        "source_ids": ["merck_pid", "cdc_pid"],
    },
    {
        "slug": "acute_abnormal_uterine_bleeding",
        "name_zh": "急性異常子宮出血",
        "name_en": "Acute abnormal uterine bleeding",
        "system": "Gynecologic/Hematologic",
        "urgency": "emergent",
        "summary_zh": "大量或急性陰道/子宮出血合併昏厥、血流不穩或貧血線索時需立即分層。",
        "summary_en": "Heavy or acute vaginal or uterine bleeding with syncope, instability, or anemia clues needs immediate risk stratification.",
        "signals": {
            "vaginal_bleeding": 6,
            "hemodynamic_instability": 6,
            "syncope": 4,
            "easy_bruising_bleeding": 2,
            "fatigue": 1,
            "pelvic_pain": 1,
        },
        "synonyms": [
            "acute abnormal uterine bleeding",
            "abnormal uterine bleeding",
            "aub",
            "heavy vaginal bleeding",
            "heavy uterine bleeding",
        ],
        "ask_next": [
            "確認出血量與時間、生命徵象/昏厥、是否有妊娠檢測資訊、貧血或凝血病史、抗凝血藥、產後或停經狀態與婦科急症需求。 / Clarify bleeding volume and timing, vital signs or syncope, whether pregnancy testing information is available, anemia or bleeding disorder history, anticoagulants, postpartum or postmenopausal status, and gynecologic emergency need.",
        ],
        "source_ids": [
            "acog_acute_aub",
            "merck_vaginal_bleeding",
            "merck_abnormal_uterine_bleeding",
        ],
    },
    {
        "slug": "ovarian_torsion",
        "name_zh": "卵巢扭轉",
        "name_en": "Ovarian torsion",
        "system": "Gynecologic",
        "urgency": "emergent",
        "summary_zh": "突發單側骨盆痛、嘔吐或懷孕可能時需急症評估。",
        "summary_en": "Sudden unilateral pelvic pain with vomiting or pregnancy possibility needs urgent evaluation.",
        "signals": {"pelvic_pain": 5, "vomiting": 2, "pregnancy_possible": 1, "severe_pain": 2},
        "synonyms": ["ovarian torsion", "adnexal torsion"],
        "ask_next": ["確認疼痛突然性、單側位置、嘔吐、卵巢囊腫史、妊娠與婦科急症需求。 / Check sudden onset, unilateral location, vomiting, ovarian cyst history, pregnancy, and gynecologic emergency need."],
        "source_ids": ["merck_professional", "nice_acute_abdomen"],
    },
    {
        "slug": "testicular_torsion",
        "name_zh": "睪丸扭轉",
        "name_en": "Testicular torsion",
        "system": "Urologic",
        "urgency": "emergent",
        "summary_zh": "突發睪丸或下腹/腹股溝痛伴噁心嘔吐時需立即排除。",
        "summary_en": "Sudden testicular, lower abdominal, or groin pain with nausea/vomiting must be excluded.",
        "signals": {"abdominal_pain": 1, "vomiting": 2, "severe_pain": 3},
        "synonyms": ["testicular torsion", "torsion"],
        "ask_next": ["確認陰囊疼痛、位置、反射、發作時間、嘔吐與立即泌尿科需求。 / Check scrotal pain, position, reflex, onset time, vomiting, and urgent urology need."],
        "source_ids": ["merck_professional"],
    },
]
