"""Starter catalog for the general differential workbench.

The catalog is intentionally explicit and conservative. It is not a complete
disease database; it is the first source-linked layer for the stepwise generic
workflow.
"""

CATALOG_VERSION = "general-differential-starter-2026-06-28"

URGENCY_ORDER = {
    "emergent": 0,
    "urgent": 1,
    "soon": 2,
    "routine": 3,
}

SOURCES = {
    "aha_heart_attack": {
        "publisher": "American Heart Association",
        "title": "Warning Signs of a Heart Attack",
        "url": "https://www.heart.org/en/health-topics/heart-attack/warning-signs-of-a-heart-attack",
    },
    "asa_stroke": {
        "publisher": "American Stroke Association",
        "title": "Stroke Symptoms and Warning Signs",
        "url": "https://www.stroke.org/en/about-stroke/stroke-symptoms",
    },
    "cdc_sepsis": {
        "publisher": "CDC",
        "title": "Sepsis",
        "url": "https://www.cdc.gov/sepsis/index.html",
    },
    "cdc_sepsis_signs": {
        "publisher": "CDC",
        "title": "Sepsis Signs and Symptoms",
        "url": "https://www.cdc.gov/sepsis/communication-resources/gaos-signs-symptoms.html",
    },
    "nice_chest_pain": {
        "publisher": "NICE CKS",
        "title": "Chest pain",
        "url": "https://cks.nice.org.uk/topics/chest-pain/",
    },
    "nice_acute_abdomen": {
        "publisher": "NICE CKS",
        "title": "Abdominal pain - acute",
        "url": "https://cks.nice.org.uk/topics/abdominal-pain-acute/",
    },
    "merck_professional": {
        "publisher": "Merck Manual Professional",
        "title": "Professional clinical reference",
        "url": "https://www.merckmanuals.com/professional",
    },
    "merck_headache_red_flags": {
        "publisher": "Merck Manual Professional",
        "title": "Matching Red Flag Findings With a Cause for Headache",
        "url": "https://www.merckmanuals.com/professional/multimedia/table/matching-red-flag-findings-with-a-cause-for-headache",
    },
}

FINDING_GROUPS = [
    {
        "group_zh": "立即安全狀態",
        "group_en": "Immediate safety",
        "findings": [
            ("hemodynamic_instability", "Hemodynamic instability", "血流動力不穩"),
            ("altered_mental_status", "Altered mental status", "意識或精神狀態改變"),
            ("respiratory_distress", "Respiratory distress", "呼吸窘迫"),
            ("severe_pain", "Severe pain", "劇烈疼痛"),
            ("syncope", "Syncope", "昏厥"),
            ("immunocompromised", "Immunocompromised", "免疫低下"),
            ("pregnancy_possible", "Pregnancy possible", "可能懷孕"),
            ("recent_trauma", "Recent trauma", "近期外傷"),
        ],
    },
    {
        "group_zh": "心肺",
        "group_en": "Cardiopulmonary",
        "findings": [
            ("chest_pain", "Chest pain", "胸痛"),
            ("dyspnea", "Dyspnea", "呼吸困難"),
            ("diaphoresis", "Diaphoresis", "冒冷汗"),
            ("radiating_arm_jaw_pain", "Arm or jaw radiation", "手臂或下顎放射痛"),
            ("pleuritic_pain", "Pleuritic pain", "吸氣或胸膜性疼痛"),
            ("hemoptysis", "Hemoptysis", "咳血"),
            ("unilateral_leg_swelling", "Unilateral leg swelling", "單側下肢腫脹"),
            ("tearing_back_pain", "Tearing back pain", "撕裂樣背痛"),
            ("orthopnea_edema", "Orthopnea or edema", "端坐呼吸或水腫"),
            ("wheeze", "Wheeze", "喘鳴"),
            ("cough_sputum", "Cough or sputum", "咳嗽或痰"),
            ("tachycardia", "Tachycardia", "心搏過速"),
        ],
    },
    {
        "group_zh": "神經與頭痛",
        "group_en": "Neurologic and headache",
        "findings": [
            ("neurologic_deficit", "Neurologic deficit", "神經學缺損"),
            ("unilateral_weakness", "Unilateral weakness", "單側無力"),
            ("speech_vision_changes", "Speech or vision changes", "言語或視覺改變"),
            ("thunderclap_headache", "Thunderclap headache", "雷擊樣頭痛"),
            ("neck_stiffness", "Neck stiffness", "頸部僵硬"),
            ("new_headache_after_50", "New headache after age 50", "50歲後新發頭痛"),
            ("jaw_claudication", "Jaw claudication", "下顎跛行"),
            ("eye_pain_redness", "Eye pain or redness", "眼痛或紅眼"),
        ],
    },
    {
        "group_zh": "腹部與泌尿",
        "group_en": "Abdominal and urinary",
        "findings": [
            ("abdominal_pain", "Abdominal pain", "腹痛"),
            ("rebound_guarding", "Rebound or guarding", "反彈痛或防禦"),
            ("rlq_pain", "Right lower quadrant pain", "右下腹痛"),
            ("ruq_pain", "Right upper quadrant pain", "右上腹痛"),
            ("postprandial_ruq_pain", "Postprandial RUQ pain", "飯後右上腹痛"),
            ("vomiting", "Vomiting", "嘔吐"),
            ("gi_bleeding", "GI bleeding", "腸胃道出血"),
            ("jaundice", "Jaundice", "黃疸"),
            ("dysuria", "Dysuria", "排尿疼痛"),
            ("flank_pain", "Flank pain", "腰側痛"),
            ("pelvic_pain", "Pelvic pain", "骨盆痛"),
        ],
    },
    {
        "group_zh": "感染、代謝與皮膚",
        "group_en": "Infectious, metabolic, skin",
        "findings": [
            ("fever", "Fever", "發燒"),
            ("hypothermia", "Hypothermia", "低體溫"),
            ("rash", "Rash", "皮疹"),
            ("facial_lip_tongue_swelling", "Face, lip, or tongue swelling", "臉唇舌腫"),
            ("extreme_thirst_polyuria", "Thirst or polyuria", "多渴或多尿"),
            ("hypoglycemia_risk", "Hypoglycemia risk", "低血糖風險"),
            ("weight_loss", "Weight loss", "體重減輕"),
            ("fatigue", "Fatigue", "疲倦"),
        ],
    },
]

DEFAULT_ASK_NEXT = [
    "先確認 ABC、生命徵象、血氧、意識狀態與是否需要急救處置。 / First confirm ABCs, vital signs, oxygen saturation, mental status, and need for emergency care.",
    "確認症狀開始時間、進展速度、最嚴重位置與是否有突然惡化。 / Clarify onset time, tempo, worst location, and sudden deterioration.",
    "確認懷孕可能、免疫低下、抗凝血藥、重大共病與近期手術或外傷。 / Check pregnancy possibility, immunocompromise, anticoagulants, major comorbidities, recent surgery, or trauma.",
    "依主要系統補問紅旗，再決定是否需要急診、影像、心電圖或實驗室檢查。 / Ask system-specific red flags, then decide on ED referral, imaging, ECG, or labs.",
]

CONDITIONS = [
    {
        "slug": "acute_coronary_syndrome",
        "name_zh": "急性冠心症",
        "name_en": "Acute coronary syndrome",
        "system": "Cardiovascular",
        "urgency": "emergent",
        "summary_zh": "胸痛合併呼吸困難、冒冷汗、手臂或下顎放射痛時需優先排除。",
        "summary_en": "Prioritize when chest pain occurs with dyspnea, diaphoresis, or arm/jaw radiation.",
        "signals": {
            "chest_pain": 4,
            "dyspnea": 2,
            "diaphoresis": 3,
            "radiating_arm_jaw_pain": 4,
            "hemodynamic_instability": 4,
            "syncope": 2,
        },
        "synonyms": ["heart attack", "myocardial infarction", "acs", "angina"],
        "ask_next": [
            "立即確認心電圖 ECG、血壓、血氧、疼痛開始時間與是否持續。 / Check ECG, blood pressure, oxygen saturation, onset time, and whether pain persists.",
            "補問冒冷汗、噁心、下顎或手臂放射痛、既往冠心病與危險因子。 / Ask about diaphoresis, nausea, jaw/arm radiation, CAD history, and risk factors.",
        ],
        "source_ids": ["aha_heart_attack", "nice_chest_pain"],
    },
    {
        "slug": "stroke_tia",
        "name_zh": "中風或短暫性腦缺血",
        "name_en": "Stroke or TIA",
        "system": "Neurologic",
        "urgency": "emergent",
        "summary_zh": "突發單側無力、言語或視覺改變、神經學缺損需立即處理。",
        "summary_en": "Sudden unilateral weakness, speech/vision changes, or focal deficit require urgent action.",
        "signals": {
            "neurologic_deficit": 4,
            "unilateral_weakness": 5,
            "speech_vision_changes": 5,
            "altered_mental_status": 2,
            "syncope": 1,
        },
        "synonyms": ["stroke", "tia", "cva", "mini stroke"],
        "ask_next": [
            "確認最後正常時間、FAST/BE-FAST 徵象、抗凝血藥與血糖。 / Confirm last-known-well time, FAST/BE-FAST signs, anticoagulants, and glucose.",
            "不要延誤急性中風流程；需要急診/中風團隊評估。 / Do not delay acute stroke pathway evaluation.",
        ],
        "source_ids": ["asa_stroke"],
    },
    {
        "slug": "sepsis",
        "name_zh": "敗血症",
        "name_en": "Sepsis",
        "system": "Infectious",
        "urgency": "emergent",
        "summary_zh": "感染表現合併意識改變、呼吸困難、低血壓或心搏過速時需優先排除。",
        "summary_en": "Suspect when infection features occur with confusion, dyspnea, hypotension, or tachycardia.",
        "signals": {
            "fever": 3,
            "hypothermia": 3,
            "altered_mental_status": 4,
            "tachycardia": 3,
            "dyspnea": 2,
            "hemodynamic_instability": 5,
            "immunocompromised": 2,
            "severe_pain": 1,
        },
        "synonyms": ["sepsis", "septic shock", "infection shock"],
        "ask_next": [
            "確認感染來源、血壓、呼吸頻率、尿量、乳酸與器官灌流狀態。 / Check infection source, blood pressure, respiratory rate, urine output, lactate, and perfusion.",
            "若不穩定，依急症流程處理，不等待完整鑑別列表。 / If unstable, follow emergency care pathways without waiting for a full list.",
        ],
        "source_ids": ["cdc_sepsis", "cdc_sepsis_signs"],
    },
    {
        "slug": "pulmonary_embolism",
        "name_zh": "肺栓塞",
        "name_en": "Pulmonary embolism",
        "system": "Cardiopulmonary",
        "urgency": "emergent",
        "summary_zh": "呼吸困難、胸膜性胸痛、咳血、單側腿腫或心搏過速時需考慮。",
        "summary_en": "Consider with dyspnea, pleuritic pain, hemoptysis, unilateral leg swelling, or tachycardia.",
        "signals": {
            "dyspnea": 4,
            "pleuritic_pain": 3,
            "hemoptysis": 3,
            "unilateral_leg_swelling": 3,
            "tachycardia": 2,
            "chest_pain": 2,
            "hemodynamic_instability": 4,
        },
        "synonyms": ["pe", "pulmonary embolus", "embolism"],
        "ask_next": [
            "確認 VTE 風險、近期手術/臥床、癌症、懷孕、血氧與是否休克。 / Check VTE risks, recent surgery/immobility, cancer, pregnancy, oxygenation, and shock.",
        ],
        "source_ids": ["nice_chest_pain", "merck_professional"],
    },
    {
        "slug": "aortic_dissection",
        "name_zh": "主動脈剝離",
        "name_en": "Aortic dissection",
        "system": "Cardiovascular",
        "urgency": "emergent",
        "summary_zh": "撕裂樣胸背痛、神經症狀、昏厥或血流不穩需立即排除。",
        "summary_en": "Tearing chest/back pain with neurologic symptoms, syncope, or instability is high risk.",
        "signals": {
            "chest_pain": 3,
            "tearing_back_pain": 5,
            "syncope": 2,
            "neurologic_deficit": 2,
            "hemodynamic_instability": 4,
        },
        "synonyms": ["dissection", "aortic catastrophe"],
        "ask_next": [
            "確認疼痛是否突然、撕裂或移動，雙側血壓/脈搏差、神經缺損與馬凡特徵。 / Clarify sudden tearing/migrating pain, pulse/BP differential, neurologic deficits, and connective tissue risk.",
        ],
        "source_ids": ["nice_chest_pain", "merck_professional"],
    },
    {
        "slug": "meningitis",
        "name_zh": "腦膜炎",
        "name_en": "Meningitis",
        "system": "Neurologic/Infectious",
        "urgency": "emergent",
        "summary_zh": "發燒、頸部僵硬、意識改變或免疫低下合併頭痛時需考慮。",
        "summary_en": "Consider with fever, neck stiffness, altered mental status, or immunocompromise.",
        "signals": {
            "fever": 3,
            "neck_stiffness": 5,
            "altered_mental_status": 4,
            "immunocompromised": 2,
            "severe_pain": 1,
        },
        "synonyms": ["meningitis", "cns infection"],
        "ask_next": [
            "確認皮疹、光畏、免疫狀態、抗生素前血培與是否需要急診處置。 / Ask about rash, photophobia, immune status, cultures before antibiotics, and emergency care needs.",
        ],
        "source_ids": ["merck_headache_red_flags", "merck_professional"],
    },
    {
        "slug": "subarachnoid_hemorrhage",
        "name_zh": "蜘蛛膜下腔出血",
        "name_en": "Subarachnoid hemorrhage",
        "system": "Neurologic",
        "urgency": "emergent",
        "summary_zh": "雷擊樣頭痛或數秒內達最痛程度時必須優先排除。",
        "summary_en": "Thunderclap headache or maximal intensity within seconds is a must-not-miss pattern.",
        "signals": {
            "thunderclap_headache": 6,
            "neck_stiffness": 2,
            "altered_mental_status": 2,
            "neurologic_deficit": 2,
            "severe_pain": 2,
        },
        "synonyms": ["sah", "subarachnoid bleed", "thunderclap"],
        "ask_next": [
            "確認達峰時間、昏厥、頸部僵硬、抗凝血藥與神經缺損。 / Confirm time to peak, syncope, neck stiffness, anticoagulants, and neurologic deficits.",
        ],
        "source_ids": ["merck_headache_red_flags"],
    },
    {
        "slug": "appendicitis",
        "name_zh": "闌尾炎",
        "name_en": "Appendicitis",
        "system": "Abdominal",
        "urgency": "urgent",
        "summary_zh": "右下腹痛、發燒、嘔吐或反彈痛時需納入。",
        "summary_en": "Include with right lower quadrant pain, fever, vomiting, or peritoneal signs.",
        "signals": {
            "abdominal_pain": 2,
            "rlq_pain": 5,
            "fever": 2,
            "vomiting": 2,
            "rebound_guarding": 3,
        },
        "synonyms": ["appendix", "rlq"],
        "ask_next": [
            "確認疼痛移轉、食慾、反彈痛、防禦、懷孕可能與是否需影像/外科評估。 / Ask about migration, appetite, rebound/guarding, pregnancy possibility, imaging, and surgical evaluation.",
        ],
        "source_ids": ["nice_acute_abdomen"],
    },
    {
        "slug": "ectopic_pregnancy",
        "name_zh": "子宮外孕",
        "name_en": "Ectopic pregnancy",
        "system": "Obstetric/Gynecologic",
        "urgency": "emergent",
        "summary_zh": "可能懷孕者出現骨盆或腹痛、昏厥或血流不穩時不可漏掉。",
        "summary_en": "Must not miss in possible pregnancy with pelvic/abdominal pain, syncope, or instability.",
        "signals": {
            "pregnancy_possible": 5,
            "pelvic_pain": 4,
            "abdominal_pain": 2,
            "syncope": 3,
            "hemodynamic_instability": 4,
        },
        "synonyms": ["ectopic", "tubal pregnancy"],
        "ask_next": [
            "確認妊娠狀態、末次月經、陰道出血、暈厥與血流動力。 / Confirm pregnancy status, LMP, vaginal bleeding, syncope, and hemodynamics.",
        ],
        "source_ids": ["nice_acute_abdomen", "merck_professional"],
    },
    {
        "slug": "anaphylaxis",
        "name_zh": "過敏性休克",
        "name_en": "Anaphylaxis",
        "system": "Allergy/Emergency",
        "urgency": "emergent",
        "summary_zh": "臉唇舌腫、皮疹、呼吸窘迫或血流不穩需立即處置。",
        "summary_en": "Facial/lip/tongue swelling, rash, respiratory distress, or instability needs immediate action.",
        "signals": {
            "facial_lip_tongue_swelling": 5,
            "rash": 3,
            "respiratory_distress": 5,
            "wheeze": 2,
            "hemodynamic_instability": 4,
        },
        "synonyms": ["anaphylaxis", "allergic shock", "angioedema"],
        "ask_next": [
            "確認暴露物、氣道腫脹、喘鳴、血壓與是否需立即急救。 / Identify exposure, airway swelling, wheeze, blood pressure, and emergency treatment need.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "pneumonia",
        "name_zh": "肺炎",
        "name_en": "Pneumonia",
        "system": "Respiratory/Infectious",
        "urgency": "urgent",
        "summary_zh": "發燒、咳嗽痰、呼吸困難或低氧表現時需考慮。",
        "summary_en": "Consider with fever, cough/sputum, dyspnea, or hypoxemia features.",
        "signals": {"fever": 3, "cough_sputum": 4, "dyspnea": 3, "tachycardia": 1},
        "synonyms": ["pneumonia", "lung infection"],
        "ask_next": [
            "確認血氧、呼吸頻率、胸痛、痰性質、共病與是否需要影像。 / Check oxygenation, respiratory rate, chest pain, sputum, comorbidities, and imaging need.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "heart_failure_exacerbation",
        "name_zh": "心衰竭惡化",
        "name_en": "Heart failure exacerbation",
        "system": "Cardiovascular",
        "urgency": "urgent",
        "summary_zh": "呼吸困難合併端坐呼吸、水腫或胸痛時需考慮。",
        "summary_en": "Dyspnea with orthopnea, edema, or chest pain may reflect heart failure exacerbation.",
        "signals": {"dyspnea": 3, "orthopnea_edema": 5, "chest_pain": 1, "tachycardia": 1},
        "synonyms": ["heart failure", "chf", "pulmonary edema"],
        "ask_next": [
            "確認體重變化、端坐呼吸、下肢水腫、心臟病史、血氧與胸痛。 / Ask about weight change, orthopnea, edema, cardiac history, oxygenation, and chest pain.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "asthma_copd_exacerbation",
        "name_zh": "氣喘或 COPD 急性惡化",
        "name_en": "Asthma or COPD exacerbation",
        "system": "Respiratory",
        "urgency": "urgent",
        "summary_zh": "喘鳴、呼吸困難、咳嗽痰或呼吸窘迫時需納入。",
        "summary_en": "Wheeze, dyspnea, cough/sputum, or respiratory distress should trigger this pathway.",
        "signals": {"wheeze": 5, "dyspnea": 3, "cough_sputum": 2, "respiratory_distress": 4},
        "synonyms": ["asthma", "copd", "bronchospasm"],
        "ask_next": [
            "確認既往氣喘/COPD、吸入藥反應、血氧、說話能力與沉默胸。 / Check asthma/COPD history, inhaler response, oxygenation, speech ability, and silent chest.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "acute_angle_closure_glaucoma",
        "name_zh": "急性隅角閉鎖性青光眼",
        "name_en": "Acute angle-closure glaucoma",
        "system": "Ophthalmologic",
        "urgency": "emergent",
        "summary_zh": "眼痛、紅眼、頭痛、噁心或視覺改變時需急症處理。",
        "summary_en": "Eye pain/redness with headache, nausea, or vision change can be an emergency.",
        "signals": {"eye_pain_redness": 5, "severe_pain": 2, "vomiting": 1, "speech_vision_changes": 2},
        "synonyms": ["glaucoma", "acute glaucoma"],
        "ask_next": [
            "確認視力、瞳孔、眼壓風險、噁心嘔吐與是否需眼科急診。 / Check vision, pupil, IOP risk, nausea/vomiting, and urgent ophthalmology need.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "gi_bleed",
        "name_zh": "腸胃道出血",
        "name_en": "Gastrointestinal bleeding",
        "system": "Gastrointestinal",
        "urgency": "urgent",
        "summary_zh": "黑便、吐血、血便、昏厥或血流不穩時需優先評估。",
        "summary_en": "Melena, hematemesis, hematochezia, syncope, or instability requires prompt assessment.",
        "signals": {"gi_bleeding": 5, "syncope": 2, "hemodynamic_instability": 4, "abdominal_pain": 1},
        "synonyms": ["gi bleed", "melena", "hematemesis"],
        "ask_next": [
            "確認出血型態、量、抗凝血藥、血壓心跳、貧血症狀與肝病史。 / Clarify bleeding type/volume, anticoagulants, vitals, anemia symptoms, and liver disease.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "diabetic_ketoacidosis",
        "name_zh": "糖尿病酮酸中毒",
        "name_en": "Diabetic ketoacidosis",
        "system": "Metabolic",
        "urgency": "emergent",
        "summary_zh": "多渴多尿、嘔吐、腹痛、意識改變或呼吸異常時需考慮。",
        "summary_en": "Thirst/polyuria with vomiting, abdominal pain, altered mental status, or abnormal breathing is high risk.",
        "signals": {
            "extreme_thirst_polyuria": 4,
            "vomiting": 2,
            "abdominal_pain": 2,
            "altered_mental_status": 3,
            "respiratory_distress": 2,
        },
        "synonyms": ["dka", "ketoacidosis", "diabetic ketoacidosis"],
        "ask_next": [
            "確認血糖、酮體、脫水、感染誘因、胰島素中斷與意識狀態。 / Check glucose, ketones, dehydration, infection triggers, insulin omission, and mental status.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "hypoglycemia",
        "name_zh": "低血糖",
        "name_en": "Hypoglycemia",
        "system": "Metabolic",
        "urgency": "emergent",
        "summary_zh": "意識改變、昏厥、冒汗或低血糖風險者需立即確認血糖。",
        "summary_en": "Altered mental status, syncope, sweating, or hypoglycemia risk should trigger glucose check.",
        "signals": {"hypoglycemia_risk": 5, "altered_mental_status": 4, "syncope": 2, "diaphoresis": 2},
        "synonyms": ["low glucose", "low blood sugar", "hypoglycemia"],
        "ask_next": [
            "立即確認指尖血糖、糖尿病藥物、進食狀況與意識安全。 / Check point-of-care glucose, diabetes medications, intake, and mental status safety.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "temporal_arteritis",
        "name_zh": "巨細胞動脈炎",
        "name_en": "Giant cell arteritis",
        "system": "Vascular/Rheumatologic",
        "urgency": "urgent",
        "summary_zh": "50歲後新發頭痛、下顎跛行或視覺症狀時需優先排除。",
        "summary_en": "New headache after age 50 with jaw claudication or visual symptoms is high risk.",
        "signals": {
            "new_headache_after_50": 5,
            "jaw_claudication": 4,
            "speech_vision_changes": 2,
            "severe_pain": 1,
        },
        "synonyms": ["giant cell arteritis", "temporal arteritis", "gca"],
        "ask_next": [
            "確認年齡、顳部壓痛、下顎跛行、視覺症狀與近端肌痛。 / Confirm age, temporal tenderness, jaw claudication, visual symptoms, and proximal myalgia.",
        ],
        "source_ids": ["merck_headache_red_flags"],
    },
    {
        "slug": "pyelonephritis",
        "name_zh": "腎盂腎炎",
        "name_en": "Pyelonephritis",
        "system": "Urinary/Infectious",
        "urgency": "urgent",
        "summary_zh": "發燒、腰側痛與排尿症狀支持上泌尿道感染。",
        "summary_en": "Fever, flank pain, and urinary symptoms support upper urinary tract infection.",
        "signals": {"fever": 3, "flank_pain": 4, "dysuria": 3, "vomiting": 1, "pregnancy_possible": 1},
        "synonyms": ["kidney infection", "pyelo", "pyelonephritis"],
        "ask_next": [
            "確認發燒、腰側敲痛、排尿症狀、懷孕、敗血症徵象與嘔吐。 / Ask about fever, CVA tenderness, urinary symptoms, pregnancy, sepsis signs, and vomiting.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "biliary_disease",
        "name_zh": "膽道疾病或膽囊炎",
        "name_en": "Biliary disease or cholecystitis",
        "system": "Gastrointestinal",
        "urgency": "urgent",
        "summary_zh": "右上腹痛、飯後疼痛、發燒或黃疸時需考慮膽道疾病。",
        "summary_en": "RUQ pain, postprandial pain, fever, or jaundice suggests biliary pathology.",
        "signals": {"ruq_pain": 4, "postprandial_ruq_pain": 3, "fever": 2, "jaundice": 3, "vomiting": 1},
        "synonyms": ["cholecystitis", "cholangitis", "gallbladder", "biliary"],
        "ask_next": [
            "確認黃疸、發燒、Murphy sign、飯後痛、肝膽胰檢驗與是否感染。 / Check jaundice, fever, Murphy sign, postprandial pain, hepatobiliary labs, and infection.",
        ],
        "source_ids": ["nice_acute_abdomen", "merck_professional"],
    },
    {
        "slug": "viral_respiratory_infection",
        "name_zh": "病毒性呼吸道感染",
        "name_en": "Viral respiratory infection",
        "system": "Respiratory/Infectious",
        "urgency": "routine",
        "summary_zh": "咳嗽、發燒、疲倦但無不穩定或呼吸窘迫時列入常見原因。",
        "summary_en": "Common when cough, fever, and fatigue occur without instability or respiratory distress.",
        "signals": {"cough_sputum": 3, "fever": 2, "fatigue": 1},
        "synonyms": ["cold", "flu", "covid", "viral infection"],
        "ask_next": [
            "確認血氧、呼吸窘迫、免疫狀態、暴露史與需要檢測或隔離。 / Check oxygenation, distress, immune status, exposure, and testing/isolation needs.",
        ],
        "source_ids": ["merck_professional"],
    },
    {
        "slug": "panic_anxiety",
        "name_zh": "恐慌或焦慮相關症狀",
        "name_en": "Panic or anxiety-related symptoms",
        "system": "Mental health",
        "urgency": "soon",
        "summary_zh": "在排除急性心肺、神經、代謝風險後，可納入焦慮或恐慌。",
        "summary_en": "Consider only after acute cardiopulmonary, neurologic, and metabolic risks are addressed.",
        "signals": {"dyspnea": 1, "chest_pain": 1, "tachycardia": 1, "diaphoresis": 1},
        "synonyms": ["panic", "anxiety", "panic attack"],
        "ask_next": [
            "先確認沒有 ACS、肺栓塞、低血糖、甲狀腺或物質相關風險。 / First rule out ACS, PE, hypoglycemia, thyroid, or substance-related risk.",
        ],
        "source_ids": ["merck_professional"],
    },
]
